BEGIN;
SELECT no_plan();
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claims','{"sub":"b2222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
CREATE TEMP TABLE income_test AS SELECT api.create_appointment('11111111-1111-4111-8111-111111111111','f1111111-1111-4111-8111-111111111111','b2222222-2222-4222-8222-222222222222',now()+interval '123 days',45::smallint,'America/Argentina/Cordoba','in_person',10000::numeric,'ARS',NULL::text) AS id,gen_random_uuid() AS request;
SELECT lives_ok($$SELECT api.record_income_movement(id,request,4000,CURRENT_DATE,'cash') FROM income_test$$,'Partial payment saved');
SELECT lives_ok($$SELECT api.record_income_movement(id,request,4000,CURRENT_DATE,'cash') FROM income_test$$,'Retry idempotent');
SELECT is((SELECT count(*) FROM api.income_movements WHERE appointment_id=(SELECT id FROM income_test)),1::bigint,'No duplicate movement');
SELECT throws_ok($$SELECT api.record_income_movement(id,gen_random_uuid(),7000,CURRENT_DATE,'cash') FROM income_test$$,NULL,NULL,'Excess payment rejected');
SELECT throws_ok($$SELECT api.record_income_movement(id,gen_random_uuid(),100,CURRENT_DATE+1,'cash') FROM income_test$$,NULL,NULL,'Future date rejected');
SELECT lives_ok($$SELECT api.record_income_movement(appointment_id,gen_random_uuid(),1000,CURRENT_DATE,'cash',id) FROM api.income_movements WHERE appointment_id=(SELECT id FROM income_test) AND movement_kind='payment'$$,'Partial refund saved');
SELECT throws_ok($$SELECT api.record_income_movement(appointment_id,gen_random_uuid(),3500,CURRENT_DATE,'cash',id) FROM api.income_movements WHERE appointment_id=(SELECT id FROM income_test) AND movement_kind='payment'$$,NULL,NULL,'Excess refund rejected');
SELECT lives_ok($$SELECT api.record_income_movement(appointment_id,gen_random_uuid(),3000,CURRENT_DATE,'cash',id) FROM api.income_movements WHERE appointment_id=(SELECT id FROM income_test) AND movement_kind='payment'$$,'Refund remaining amount');
SELECT is((SELECT payment_status FROM api.appointments WHERE id=(SELECT id FROM income_test)),'refunded','Full refund reflected');
SELECT set_config('request.jwt.claims','{"sub":"d1111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
SELECT is((SELECT count(*) FROM api.income_movements),0::bigint,'Patient cannot read financial movements');
SELECT throws_ok($$SELECT api.record_income_movement(id,gen_random_uuid(),100,CURRENT_DATE,'cash') FROM income_test$$,NULL,NULL,'Patient cannot register payment');
SELECT * FROM finish();
ROLLBACK;
