BEGIN;
SELECT no_plan();
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claims','{"sub":"b2222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
CREATE TEMP TABLE income_fix AS SELECT api.create_appointment('11111111-1111-4111-8111-111111111111','f1111111-1111-4111-8111-111111111111','b2222222-2222-4222-8222-222222222222',now()+interval '129 days',45::smallint,'America/Argentina/Cordoba','in_person',10000::numeric,'ARS',NULL::text) AS id,gen_random_uuid() AS request;
ALTER TABLE income_fix ADD COLUMN payment uuid;
UPDATE income_fix SET payment=api.record_income_movement(id,gen_random_uuid(),4000,CURRENT_DATE-2,'cash');
SELECT lives_ok($$SELECT api.correct_income_payment(payment,payment,request,5000,CURRENT_DATE-1,'transfer') FROM income_fix$$,'Correct without reason');
SELECT lives_ok($$SELECT api.correct_income_payment(payment,payment,request,5000,CURRENT_DATE-1,'transfer') FROM income_fix$$,'Retry correction idempotent');
SELECT is((SELECT count(*) FROM api.income_movements WHERE appointment_id=(SELECT id FROM income_fix)),1::bigint,'Correction does not appear as refund');
SELECT is((SELECT amount FROM api.income_movements WHERE id=(SELECT payment FROM income_fix)),5000::numeric,'Effective payment updated');
SELECT is((SELECT amount FROM app.appointment_payment_movements WHERE id=(SELECT payment FROM income_fix)),4000::numeric,'Original immutable');
SELECT is((SELECT total_paid FROM api.appointments WHERE id=(SELECT id FROM income_fix)),5000::numeric,'Appointment shares corrected total');
SELECT throws_ok($$SELECT api.correct_income_payment(payment,payment,gen_random_uuid(),4500,CURRENT_DATE,'cash') FROM income_fix$$,NULL,NULL,'Stale revision rejected');
SELECT throws_ok($$SELECT api.correct_income_payment(payment,payment,request,5500,CURRENT_DATE-1,'transfer') FROM income_fix$$,NULL,NULL,'Request cannot be reused for different payload');
SELECT lives_ok($$SELECT api.record_income_movement(id,gen_random_uuid(),2000,CURRENT_DATE,'cash',payment) FROM income_fix$$,'Refund corrected root payment');
SELECT throws_ok($$SELECT api.correct_income_payment(m.id,m.revision_id,gen_random_uuid(),1500,CURRENT_DATE,'cash') FROM api.income_movements m WHERE m.id=(SELECT payment FROM income_fix)$$,NULL,NULL,'Cannot correct below refunded amount');
SELECT throws_ok($$SELECT api.correct_income_payment(m.id,m.revision_id,gen_random_uuid(),15000,CURRENT_DATE,'cash') FROM api.income_movements m WHERE m.id=(SELECT payment FROM income_fix)$$,NULL,NULL,'Correction cannot exceed appointment balance');
SELECT throws_ok($$SELECT api.correct_income_payment(m.id,m.revision_id,gen_random_uuid(),3000,CURRENT_DATE+2,'cash') FROM api.income_movements m WHERE m.id=(SELECT payment FROM income_fix)$$,NULL,NULL,'Future date rejected');
SELECT lives_ok($$SELECT api.correct_income_payment(m.id,m.revision_id,gen_random_uuid(),3000,CURRENT_DATE-1,'cash') FROM api.income_movements m WHERE m.id=(SELECT payment FROM income_fix)$$,'Second correction preserves refund');
SELECT throws_ok($$SELECT api.record_income_movement(id,gen_random_uuid(),1001,CURRENT_DATE,'cash',payment) FROM income_fix$$,NULL,NULL,'Refund limited by corrected amount');
SELECT lives_ok($$SELECT api.record_income_movement(id,gen_random_uuid(),1000,CURRENT_DATE,'cash',payment) FROM income_fix$$,'Refund final corrected balance');
SELECT is((SELECT payment_status FROM api.appointments WHERE id=(SELECT id FROM income_fix)),'refunded','Full refund reflected after corrections');
SELECT set_config('request.jwt.claims','{"sub":"b1111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
SELECT lives_ok($$SELECT api.correct_income_payment(m.id,m.revision_id,gen_random_uuid(),3000,CURRENT_DATE-1,'transfer') FROM api.income_movements m WHERE m.id=(SELECT payment FROM income_fix)$$,'Owner can correct operational payment');
SELECT set_config('request.jwt.claims','{"sub":"a0000000-0000-4000-8000-000000000000","role":"authenticated"}',true);
SELECT is((SELECT count(*) FROM api.income_movements),0::bigint,'Platform Admin cannot read corrections');
SELECT throws_ok($$SELECT api.correct_income_payment(payment,payment,gen_random_uuid(),3000,CURRENT_DATE,'cash') FROM income_fix$$,NULL,NULL,'Platform Admin cannot correct');
SELECT set_config('request.jwt.claims','{"sub":"d1111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
SELECT is((SELECT count(*) FROM api.income_movements),0::bigint,'Patient cannot read corrections');
SELECT throws_ok($$SELECT api.correct_income_payment(payment,payment,gen_random_uuid(),3000,CURRENT_DATE,'cash') FROM income_fix$$,NULL,NULL,'Patient cannot correct');
SELECT set_config('request.jwt.claims','{"sub":"b3333333-3333-4333-8333-333333333333","role":"authenticated"}',true);
SELECT throws_ok($$SELECT api.correct_income_payment(payment,payment,gen_random_uuid(),3000,CURRENT_DATE,'cash') FROM income_fix$$,NULL,NULL,'Unassigned identity cannot correct');
SELECT * FROM finish();
ROLLBACK;
