BEGIN;
SELECT no_plan();
UPDATE app.check_in_assignments SET status='cancelled' WHERE patient_id='f1111111-1111-4111-8111-111111111111' AND status='pending';
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claims','{"sub":"b2222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
CREATE TEMP TABLE question_fixture AS SELECT '11111111-1111-4111-8111-111111111111'::uuid org,
 '[{"id":"eeeeeeee-1111-4111-8111-111111111111","text":"Energía","type":"scale","enabled":true,"required":true,"archived":false,"options":[],"alert":{"op":"lte","values":["2"]}},{"id":"eeeeeeee-2222-4222-8222-222222222222","text":"Ayuda","type":"yesno","enabled":true,"required":false,"archived":false,"options":[],"alert":{"op":"in","values":["Sí"]}}]'::jsonb questions;
SELECT lives_ok($$SELECT api.save_checkin_questions(org,questions) FROM question_fixture$$,'Save two optional alert questions');
SELECT throws_ok($$SELECT api.save_checkin_questions(org,questions) FROM question_fixture$$,NULL,NULL,'Stale library update rejected');
SELECT throws_ok($$SELECT api.save_checkin_questions(org,questions||jsonb_build_array(jsonb_set(questions->0,'{id}',to_jsonb(gen_random_uuid()::text))),(api.get_checkin_questions(org)->>'updated_at')::timestamptz) FROM question_fixture$$,NULL,NULL,'Third alert rejected in backend');
SELECT throws_ok($$SELECT api.save_checkin_questions(org,jsonb_set(questions,'{0,type}','"text"'),(api.get_checkin_questions(org)->>'updated_at')::timestamptz) FROM question_fixture$$,NULL,NULL,'Text cannot trigger automatic alert');
SELECT throws_ok($$SELECT api.save_checkin_questions(org,jsonb_set(questions,'{0,alert,values}','["6"]'),(api.get_checkin_questions(org)->>'updated_at')::timestamptz) FROM question_fixture$$,NULL,NULL,'Invalid threshold rejected');
CREATE TEMP TABLE question_assignment AS SELECT api.assign_daily_checkin('f1111111-1111-4111-8111-111111111111',now()+interval '2 days') id;
SELECT lives_ok($$SELECT api.save_checkin_questions(org,'[]',(api.get_checkin_questions(org)->>'updated_at')::timestamptz) FROM question_fixture$$,'All questions can be removed from active library');
SELECT is((SELECT jsonb_array_length(questions) FROM api.daily_checkins WHERE id=(SELECT id FROM question_assignment)),2,'Sent questionnaire is frozen');
SELECT set_config('request.jwt.claims','{"sub":"d2222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
SELECT throws_ok($$SELECT api.submit_question_checkin(id,'{}') FROM question_assignment$$,NULL,NULL,'Other patient cannot answer');
SELECT is((SELECT count(*) FROM api.daily_checkins WHERE id=(SELECT id FROM question_assignment)),0::bigint,'Other patient cannot read snapshot');
SELECT set_config('request.jwt.claims','{"sub":"d1111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
SELECT throws_ok($$SELECT api.get_checkin_questions(org) FROM question_fixture$$,NULL,NULL,'Patient cannot read professional library');
SELECT throws_ok($$SELECT api.submit_daily_checkin(id,1::smallint,1::smallint,true,'','{}') FROM question_assignment$$,NULL,NULL,'Legacy endpoint cannot bypass questionnaire');
SELECT throws_ok($$SELECT api.submit_question_checkin(id,'{}') FROM question_assignment$$,NULL,NULL,'Required answer enforced');
SELECT throws_ok($$SELECT api.submit_question_checkin(id,'{"unknown":"yes"}') FROM question_assignment$$,NULL,NULL,'Unknown question rejected');
SELECT lives_ok($$SELECT api.submit_question_checkin(id,'{"eeeeeeee-1111-4111-8111-111111111111":"2","eeeeeeee-2222-4222-8222-222222222222":"Sí"}') FROM question_assignment$$,'Patient submits matching answers');
SELECT throws_ok($$SELECT api.submit_question_checkin(id,'{}') FROM question_assignment$$,NULL,NULL,'Second response rejected');
SELECT is((SELECT jsonb_array_length(alert_matches) FROM api.daily_checkins WHERE id=(SELECT id FROM question_assignment)),2,'Original two rules still applied after library edit');
SELECT ok((SELECT energy IS NULL AND adherence IS NULL FROM api.daily_checkins WHERE id=(SELECT id FROM question_assignment)),'No invented energy or adherence scores');
SELECT set_config('request.jwt.claims','{"sub":"b2222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
SELECT throws_ok($$SELECT api.assign_daily_checkin('f1111111-1111-4111-8111-111111111111',now()+interval '2 days')$$,NULL,NULL,'Empty library cannot be assigned');
SELECT is((SELECT count(*) FROM app.alerts WHERE response_id IN (SELECT id FROM app.check_in_responses WHERE assignment_id=(SELECT id FROM question_assignment)) AND rule_code='CUSTOM_CHECKIN'),1::bigint,'One consolidated alert, no legacy rules');
SELECT set_config('request.jwt.claims','{"sub":"a0000000-0000-4000-8000-000000000000","role":"authenticated"}',true);
SELECT throws_ok($$SELECT api.get_checkin_questions(org) FROM question_fixture$$,NULL,NULL,'Admin cannot access library');
SELECT is((SELECT count(*) FROM api.daily_checkins WHERE id=(SELECT id FROM question_assignment)),0::bigint,'Admin cannot read answers');
SELECT * FROM finish();
ROLLBACK;
