import {FreeCheckin} from '../../../components/domain/FreeCheckin';
import { CheckinHistoryEntry } from '../../../components/domain/CheckinHistoryEntry';
import { CheckinQuestionLibrary } from '../../../components/domain/CheckinQuestionLibrary';
import { QuestionCheckinForm } from '../../../components/domain/QuestionCheckinForm';
import { useCallback,useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { useAuth } from '../../../auth/AuthProvider';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Dialog } from '../../../components/ui/Dialog';
import { Badge } from '../../../components/ui/Badge';
import { RealDailyWeight } from '../../../components/domain/RealDailyWeight';
import { RealInitialMeasurements } from '../../../components/domain/RealInitialMeasurements';
import { inactivityDays,inactivityGroup } from '../../../lib/dailyFollowup';
import { localDate } from '../../../lib/anthropometry';
import { loadDaily,submitCheckin,saveList,assignList,respondTask,savePhrase,assignPhrase,type DailyData,type DailyList,type DailyTask,type DailyCheckin,type DailyPhrase } from '../../../data/supabase/daily-followup.repository';

const empty:DailyData={patients:[],weights:[],checkins:[],lists:[],tasks:[],phrases:[],assignments:[]};
const fieldNames:Record<string,string>={sleep:'Sueño',digestion:'Digestión',satiety:'Hambre y saciedad',help:'Pedido de ayuda',notes:'Comentario'};
type Section='overview'|'weight'|'checkins'|'steps'|'phrases';
const sections:Array<[Section,string]>=[['overview','Resumen'],['weight','Peso cotidiano'],['checkins','Check-ins'],['steps','Próximos pasos'],['phrases','Recomendaciones']];

export function RealDailyFollowupPage({patient=false,section='overview',embedded=false}:{patient?:boolean;section?:Section;embedded?:boolean}) {
 const {patientId:routePatient}=useParams();const {accessContext}=useAuth();
 const [data,setData]=useState<DailyData>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [tab,setTab]=useState<Section>(section);const [person,setPerson]=useState(routePatient??'');const [search,setSearch]=useState('');const [group,setGroup]=useState('');
 const [listEditor,setListEditor]=useState<DailyList|'new'|null>(null);const [phraseEditor,setPhraseEditor]=useState<DailyPhrase|'new'|null>(null);
 const [listAssignment,setListAssignment]=useState<DailyList|null>(null);const [phraseAssignment,setPhraseAssignment]=useState<DailyPhrase|null>(null);const [picked,setPicked]=useState<string[]>([]);
 const [remove,setRemove]=useState<DailyList|DailyPhrase|null>(null);const [answer,setAnswer]=useState<DailyCheckin|null>(null);
 const [checkPeriod,setCheckPeriod]=useState('all');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [priority,setPriority]=useState('');const [sort,setSort]=useState('new');
 const orgs=accessContext?.memberships.filter(m=>m.role==='nutritionist'&&m.organization_status==='active')??[];const [org,setOrg]=useState('');
 const refresh=useCallback(async()=>{setLoading(true);try{setData(await loadDaily());}catch(e){setData(empty);setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[refresh]);
 useEffect(()=>{setTab(section);setPerson(routePatient??'');},[section,routePatient]);
 const selected=data.patients.find(p=>p.id===(person||(patient?data.patients[0]?.id:undefined)));
 const orgId=org||selected?.organization_id||orgs[0]?.organization_id||'';
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await fn();await refresh();setNotice('Cambios guardados.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}};
 const latest=(id:string)=>data.checkins.find(c=>c.patient_id===id&&c.submitted_at);
 const checkPriority=(c?:DailyCheckin)=>!c?'none':c.questions?(c.alert_matches?.length?'high':'normal'):c.help_requested||Math.min(c.energy??5,c.adherence??5)<=2?'high':Math.min(c.energy??5,c.adherence??5)===3?'medium':'normal';
 const scoped=data.patients.filter(p=>(!selected||selected.id===p.id)&&`${p.first_name} ${p.last_name}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const checks=scoped.filter(p=>{
 const c=latest(p.id);if(priority&&checkPriority(c)!==priority)return false;if(checkPeriod==='all')return true;if(!c?.submitted_at)return false;
 const date=localDate(new Date(c.submitted_at));const now=new Date();let start='';if(checkPeriod==='custom'){if(!from||!to||from>to)return false;return date>=from&&date<=to;}
 if(checkPeriod==='month')start=localDate(new Date(now.getFullYear(),now.getMonth(),1));else{now.setDate(now.getDate()-Number(checkPeriod)+1);start=localDate(now);}return date>=start;
 }).sort((a,b)=>sort==='name'?a.last_name.localeCompare(b.last_name):(sort==='old'?1:-1)*(latest(a.id)?.submitted_at??'').localeCompare(latest(b.id)?.submitted_at??''));
 const history=data.checkins.filter(c=>{
 if(c.patient_id!==selected?.id)return false;
 if(patient)return true;
 if(priority&&checkPriority(c.submitted_at?c:undefined)!==priority)return false;
 if(checkPeriod==='all')return true;
 const day=localDate(new Date(c.submitted_at??c.created_at));
 if(checkPeriod==='custom')return !!from&&!!to&&from<=to&&day>=from&&day<=to;
 const now=new Date();const end=localDate(now);
 const start=checkPeriod==='month'?localDate(new Date(now.getFullYear(),now.getMonth(),1)):(now.setDate(now.getDate()-Number(checkPeriod)+1),localDate(now));
 return day>=start&&day<=end;
 }).sort((a,b)=>(sort==='old'?1:-1)*(a.submitted_at??a.created_at).localeCompare(b.submitted_at??b.created_at));
 return <div className={embedded?'space-y-5':'max-w-6xl mx-auto p-4 sm:p-6 space-y-5'}>
 {!embedded&&<>
 <Link className="inline-flex min-h-11 items-center text-brand-strong text-sm" to={patient?'/patient':'/professional/patients'}>← {patient?'Volver al inicio':'Volver a pacientes'}</Link>
 <h1 className="text-2xl font-bold">{patient?'Tu seguimiento cotidiano':'Seguimiento cotidiano'}</h1><p className="text-sm text-text-secondary">Peso, respuestas y hábitos. Antropometría conserva sus revisiones profesionales por separado.</p>
 <nav className="flex flex-wrap gap-1" aria-label="Secciones de seguimiento">{sections.map(([key,label])=><Button key={key} variant={tab===key?'primary':'ghost'} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</Button>)}</nav>
 </>}
 {loading&&<p role="status">Actualizando seguimiento…</p>}{error&&<Card><p role="alert" className="text-semantic-critical">{error}</p><Button onClick={()=>{setError('');void refresh();}}>Reintentar</Button></Card>}{notice&&<p role="status" className="text-sm text-brand-strong">{notice}</p>}
 {!embedded&&<><div className="flex flex-wrap gap-3"><label className="form-label flex-1 min-w-48">{patient?'Ficha':'Paciente'}<select className="form-control" value={selected?.id??''} onChange={e=>setPerson(e.target.value)}>{!patient&&<option value="">Todos mis pacientes</option>}{data.patients.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label>{!patient&&orgs.length>1&&<label className="form-label">Consultorio para nuevas listas/frases<select className="form-control" value={orgId} onChange={e=>setOrg(e.target.value)}>{orgs.map((m,i)=><option key={m.organization_id} value={m.organization_id}>Consultorio {i+1} · {m.organization_id.slice(0,8)}</option>)}</select></label>}</div></>}
 {!loading&&!data.patients.length&&<Card>No hay fichas con acceso activo. Las invitaciones deben aceptarse para iniciar el seguimiento del paciente.</Card>}
 {patient&&selected&&tab==='overview'&&<RealInitialMeasurements key={selected.id} patientId={selected.id} patient/>}
 {tab==='overview'&&<>
 {patient&&selected&&<Card><FreeCheckin patientId={selected.id} onSaved={refresh}/></Card>}
 {!patient&&<Card className="space-y-2"><h2 className="font-bold">Últimos 7 días</h2><p className="text-sm text-text-secondary">{scoped.filter(p=>p.last_at&&new Date(p.last_at).getTime()>=Date.now()-7*86400000).length} pacientes con actividad · {data.checkins.filter(c=>scoped.some(p=>p.id===c.patient_id)&&c.submitted_at&&new Date(c.submitted_at).getTime()>=Date.now()-7*86400000).length} check-ins respondidos</p><Button variant="secondary" onClick={()=>{setTab('checkins');setPriority('high');setCheckPeriod('7');setPerson('');}}>Revisar respuestas que necesitan atención</Button></Card>}
 {patient?<Card><h2 className="font-bold">Tus próximos pasos</h2><div className="flex flex-wrap gap-2 mt-3"><Button onClick={()=>setTab('checkins')}>Responder check-in</Button><Button variant="secondary" onClick={()=>setTab('steps')}>Ver tareas</Button><Button variant="ghost" onClick={()=>setTab('weight')}>Registrar peso</Button></div>{selected&&<p className="text-xs text-text-secondary mt-3">Última actividad registrada: {selected.last_at?new Date(selected.last_at).toLocaleString('es-AR'):'Todavía sin actividad'}</p>}</Card>:<>
 <Card className="space-y-4"><h2 className="font-bold">Resumen semanal accionable</h2><p className="text-sm text-text-secondary">Cuenta respuestas, peso, comidas, tareas y comentarios del paciente. No cuenta ingresos ni ediciones del profesional.</p><div className="grid grid-cols-3 gap-2">{['3–4','5–9','10+'].map(g=><button key={g} className="p-3 rounded-xl bg-surface-subtle text-center min-h-11" aria-pressed={group===g} onClick={()=>setGroup(group===g?'':g)}><strong className="block text-xl">{scoped.filter(p=>inactivityGroup(inactivityDays(p))===g).length}</strong><span className="text-xs">{g} días</span></button>)}</div><label className="form-label">Buscar paciente<input className="form-control" value={search} onChange={e=>setSearch(e.target.value)}/></label><p className="text-xs text-text-secondary">Sin respuestas previas, contamos desde la activación del portal. Las señales son operativas, no diagnósticos.</p></Card>
 {scoped.filter(p=>!group||inactivityGroup(inactivityDays(p))===group).sort((a,b)=>(inactivityDays(b)??-1)-(inactivityDays(a)??-1)).map(p=><Card key={p.id} className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{p.first_name} {p.last_name}</h3><p className="text-xs text-text-secondary">{inactivityDays(p)===null?'Portal aún sin activar':`${inactivityDays(p)} días sin actividad registrada`}</p>{latest(p.id)?.help_requested&&<Badge variant="high">Solicitó ayuda</Badge>}</div><div className="flex gap-2"><Button variant="secondary" onClick={()=>{setPerson(p.id);setTab('checkins');}}>Ver seguimiento</Button><Button asChild variant="ghost"><Link to={`/professional/patients/${p.id}`}>Antropometría</Link></Button></div></Card>)}
 </>}
 </>}
 {tab==='weight'&&(selected?<RealDailyWeight key={selected.id} patientId={selected.id} rows={data.weights} onSaved={refresh}/>:<Card>Elegí un paciente para consultar su peso cotidiano.</Card>)}
 {tab==='checkins'&&<>
 {!patient&&embedded&&<Card className="space-y-3"><div className="flex flex-wrap gap-1">{[['all','Todos'],['1','Hoy'],['7','7 días'],['15','15 días'],['month','Mes'],['custom','Personalizado']].map(([v,l])=><Button key={v} variant={checkPeriod===v?'secondary':'ghost'} aria-pressed={checkPeriod===v} onClick={()=>setCheckPeriod(v!)}>{l}</Button>)}</div>{checkPeriod==='custom'&&<div className="grid sm:grid-cols-2 gap-3"><label className="form-label">Desde<input className="form-control" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="form-label">Hasta<input className="form-control" type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label>{(!from||!to||from>to)&&<p className="text-sm">Completá un rango válido.</p>}</div>}<div className="grid sm:grid-cols-2 gap-3"><label className="form-label">Prioridad<select className="form-control" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Todas</option><option value="high">Alta</option><option value="medium">Media</option><option value="normal">Normal</option><option value="none">Sin respuesta</option></select></label><label className="form-label">Orden<select className="form-control" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Más reciente</option><option value="old">Más antigua</option></select></label></div><p className="text-xs text-text-secondary">{history.length} check-ins · Período según fecha de respuesta; si está pendiente, fecha de creación.</p></Card>}
 {!patient&&embedded&&<header className="space-y-1"><h2 className="font-bold">Historial de respuestas</h2><p className="text-sm text-text-secondary">Consultá lo que respondió este paciente en cada fecha. No se configuran preguntas individuales aquí.</p><Link className="inline-flex min-h-11 items-center text-sm text-brand-strong" to="/professional/settings">Configurar preguntas generales →</Link></header>}
 {patient&&selected&&<FreeCheckin patientId={selected.id} onSaved={refresh}/>}
 {!patient&&!embedded&&<>
 <Card className="space-y-3"><div className="flex flex-wrap gap-1">{[['all','Todos'],['1','Hoy'],['7','7 días'],['15','15 días'],['month','Mes'],['custom','Personalizado']].map(([v,l])=><Button key={v} variant={checkPeriod===v?'primary':'ghost'} onClick={()=>setCheckPeriod(v!)}>{l}</Button>)}</div>{checkPeriod==='custom'&&<div className="grid sm:grid-cols-2 gap-3"><label className="form-label">Desde<input className="form-control" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="form-label">Hasta<input className="form-control" type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label>{(!from||!to||from>to)&&<p>Completá un rango válido.</p>}</div>}<label className="form-label">Prioridad<select className="form-control" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Todas</option><option value="high">Alta</option><option value="medium">Media</option><option value="normal">Normal</option><option value="none">Sin respuesta</option></select></label><label className="form-label">Orden<select className="form-control" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Más reciente</option><option value="old">Más antigua</option><option value="name">Nombre</option></select></label></Card>
 {!selected&&checks.map(p=><Card key={p.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{p.first_name} {p.last_name}</strong><p className="text-sm text-text-secondary">{latest(p.id)?(latest(p.id)!.questions?`${latest(p.id)!.alert_matches?.length??0} preguntas con alerta`:`Energía ${latest(p.id)!.energy}/5 · Adherencia ${latest(p.id)!.adherence}/5`):'Sin respuestas'}</p></div><Button onClick={()=>setPerson(p.id)} variant="secondary">Ver historial</Button></div></Card>)}</>}
 {selected&&!patient&&<div className="space-y-4">{history.map((c,i)=><CheckinHistoryEntry key={c.id} value={c} initiallyOpen={i===0}/>)}</div>}
 {selected&&patient&&history.map(c=><Card key={c.id} className="space-y-3"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">Check-in · {new Date(c.created_at).toLocaleDateString('es-AR')}</h3><Badge variant={c.status==='completed'?'active':'neutral'}>{c.status==='completed'?'Respondido':c.status==='pending'&&(!c.due_date||new Date(c.due_date)>new Date())?'Pendiente':'Vencido / cerrado'}</Badge></div>{c.submitted_at?<>{c.questions?<div className="space-y-2">{c.questions.map(q=><div key={q.id} className="text-sm break-words"><b>{q.text}</b><p>{c.question_answers?.[q.id]||'Sin respuesta'}</p>{!patient&&c.alert_matches?.includes(q.id)&&<Badge variant="high">Respuesta con alerta</Badge>}</div>)}</div>:<p>Energía: {c.energy}/5 · Adherencia: {c.adherence}/5</p>}{c.help_requested&&<Badge variant="high">Pedido de ayuda</Badge>}{Object.entries(c.answers??{}).map(([k,v])=><p key={k} className="text-sm"><b>{fieldNames[k]}:</b> {v}</p>)}{c.notes&&<p className="text-sm whitespace-pre-wrap">{c.notes}</p>}</>:patient&&c.status==='pending'&&(!c.due_date||new Date(c.due_date)>new Date())&&<Button onClick={()=>setAnswer(c)}>Responder</Button>}</Card>)}
 {selected&&!history.length&&<Card>No hay check-ins para este período o filtro.</Card>}
 </>}
 {tab==='steps'&&<>
 {!patient&&<Button disabled={!orgId} onClick={()=>setListEditor('new')}>Nueva lista</Button>}
 {data.lists.filter(l=>!selected||l.patient_id===selected.id||!patient&&!l.patient_id).map(l=><Card key={l.id} className="space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{l.title}</h2><p className="text-xs text-text-secondary">{l.duration_days} días · {l.active?'Activa':'Sin aplicar'} · {data.patients.find(p=>p.id===l.patient_id)?.first_name??'Sin paciente'}</p></div>{!patient&&<div className="flex flex-wrap gap-1"><Button variant="ghost" onClick={()=>setListEditor(l)}>Editar</Button><Button variant="ghost" disabled={busy} onClick={()=>void run(()=>saveList(l.organization_id,`${l.title.slice(0,150)} (copia)`,l.duration_days,l.items.map(i=>({...i,id:crypto.randomUUID()}))))}>Duplicar</Button><Button variant="secondary" disabled={busy} onClick={()=>l.active?void run(()=>assignList(l,l.patient_id,false)):setListAssignment(l)}>{l.active?'Desaplicar':'Aplicar'}</Button><Button variant="ghost" onClick={()=>setRemove(l)}>Eliminar</Button></div>}</div>
 {l.items.map(i=><TaskRow key={`${l.id}:${i.id}`} list={l} task={i} activity={data.tasks.find(t=>t.list_id===l.id&&t.task_id===i.id)} patient={patient} onSaved={refresh}/>)}
 </Card>)}{!data.lists.length&&<Card>No hay listas de próximos pasos disponibles.</Card>}
 </>}
 {tab==='phrases'&&<>{!patient&&<Button disabled={!orgId} onClick={()=>setPhraseEditor('new')}>Nueva frase</Button>}{data.phrases.filter(f=>!patient||data.assignments.some(a=>a.phrase_id===f.id&&a.patient_id===selected?.id)).map(f=><Card key={f.id} className="flex flex-wrap gap-3 justify-between items-center"><blockquote className="min-w-0 flex-1 text-sm whitespace-pre-wrap">“{f.text}”</blockquote>{!patient&&<><p className="text-xs text-text-secondary">{data.assignments.filter(a=>a.phrase_id===f.id).map(a=>{const p=data.patients.find(p=>p.id===a.patient_id);return p?`${p.first_name} ${p.last_name}`:'';}).filter(Boolean).join(', ')||'Sin pacientes'}</p><div className="flex flex-wrap gap-1"><Button variant="ghost" onClick={()=>setPhraseEditor(f)}>Editar</Button><Button variant="ghost" disabled={busy} onClick={()=>void run(()=>savePhrase(f.organization_id,f.text))}>Duplicar</Button><Button variant="secondary" onClick={()=>{setPhraseAssignment(f);setPicked(data.assignments.filter(a=>a.phrase_id===f.id).map(a=>a.patient_id));}}>Aplicar</Button><Button variant="ghost" onClick={()=>setRemove(f)}>Eliminar</Button></div></>}</Card>)}{!data.phrases.length&&<Card>No hay recomendaciones disponibles.</Card>}</>}
 {answer?.questions&&<QuestionCheckinForm id={answer.id} questions={answer.questions} onClose={()=>setAnswer(null)} onSaved={async()=>{setAnswer(null);await refresh();}}/>}
 {answer&&!answer.questions&&<AnswerCheckin value={answer} onClose={()=>setAnswer(null)} onSaved={async()=>{setAnswer(null);await refresh();}}/>}
 {listEditor&&<ListEditor value={listEditor} org={orgId} onClose={()=>setListEditor(null)} onSaved={async()=>{setListEditor(null);await refresh();}}/>}
 {phraseEditor&&<PhraseEditor value={phraseEditor} org={orgId} onClose={()=>setPhraseEditor(null)} onSaved={async()=>{setPhraseEditor(null);await refresh();}}/>}
 <Dialog isOpen={!!listAssignment} onClose={()=>setListAssignment(null)} title="Aplicar lista" description="Reemplaza la lista activa sin borrar su historial. Una lista previamente asignada no puede cambiar de paciente."><div className="space-y-2">{data.patients.filter(p=>p.organization_id===listAssignment?.organization_id&&(!listAssignment.patient_id||listAssignment.patient_id===p.id)).map(p=><Button key={p.id} className="w-full" disabled={busy} onClick={async()=>{if(listAssignment&&await run(()=>assignList(listAssignment,p.id,true)))setListAssignment(null);}}>{p.first_name} {p.last_name}</Button>)}</div>{error&&<p role="alert">{error}</p>}</Dialog>
 <Dialog isOpen={!!phraseAssignment} onClose={()=>setPhraseAssignment(null)} title="Aplicar frase" description="Cada paciente mantiene una frase activa. Una nueva reemplaza la anterior.">{data.patients.filter(p=>p.organization_id===phraseAssignment?.organization_id).map(p=><label key={p.id} className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={picked.includes(p.id)} onChange={e=>setPicked(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id))}/>{p.first_name} {p.last_name}</label>)}{error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={async()=>{if(phraseAssignment&&await run(()=>assignPhrase(phraseAssignment.id,picked)))setPhraseAssignment(null);}}>Guardar asignación</Button></Dialog>
 <Dialog isOpen={!!remove} onClose={()=>setRemove(null)} title="Eliminar" description="Dejará de estar visible para el paciente. El historial interno se conserva.">{error&&<p role="alert">{error}</p>}<Button variant="destructive" disabled={busy} onClick={async()=>{if(remove&&await run(()=> 'items' in remove?assignList(remove,remove.patient_id,false,true):savePhrase(remove.organization_id,remove.text,remove,true)))setRemove(null);}}>Confirmar eliminación</Button></Dialog>
 </div>;
}

function TaskRow({list,task,activity,patient,onSaved}:{list:DailyList;task:DailyList['items'][number];activity?:DailyTask;patient:boolean;onSaved:()=>Promise<void>}) {
 const [comment,setComment]=useState(activity?.comment??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const save=async(completed:boolean)=>{setBusy(true);setError('');try{await respondTask(list.id,task.id,completed,comment);await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="border-t border-border-subtle py-3 space-y-2"><label className="flex gap-2 items-start"><input type="checkbox" disabled={!patient||busy} checked={activity?.completed??false} onChange={e=>void save(e.target.checked)}/><span className={activity?.completed?'line-through text-text-secondary':''}>{task.text}</span></label>{patient?<><label className="block text-xs">Comentario opcional<textarea maxLength={500} className="form-control" value={comment} onChange={e=>setComment(e.target.value)}/></label><Button variant="secondary" disabled={busy||comment===(activity?.comment??'')} onClick={()=>void save(activity?.completed??false)}>Guardar comentario</Button></>:activity?.comment&&<p className="text-sm whitespace-pre-wrap text-text-secondary">{activity.comment}</p>}{error&&<p role="alert">{error}</p>}</div>;
}

function AnswerCheckin({value,onClose,onSaved}:{value:DailyCheckin;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const [energy,setEnergy]=useState('');const [adherence,setAdherence]=useState('');const [help,setHelp]=useState(false);const [notes,setNotes]=useState('');const [answers,setAnswers]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <Dialog isOpen onClose={()=>{if(!busy)onClose();}} title="Tu check-in" description="Contanos cómo venís. Tu respuesta es privada y se envía una sola vez."><form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await submitCheckin(value.id,Number(energy),Number(adherence),help,notes,answers);await onSaved();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{[[energy,setEnergy,'Energía'],[adherence,setAdherence,'Adherencia al plan']].map(([v,set,label])=><fieldset key={String(label)}><legend className="form-label">{String(label)} · 1 baja, 5 alta</legend><div className="flex gap-2">{[1,2,3,4,5].map(n=><label key={n} className="min-h-11 min-w-11 rounded-xl bg-surface-subtle flex items-center justify-center gap-1"><input required type="radio" name={String(label)} value={n} checked={v===String(n)} onChange={()=> (set as (v:string)=>void)(String(n))}/>{n}</label>)}</div></fieldset>)}{value.daily_fields.filter(k=>['sleep','digestion','satiety'].includes(k)).map(k=><label key={k} className="block form-label">{fieldNames[k]} (opcional)<input className="form-control" maxLength={200} value={answers[k]??''} onChange={e=>setAnswers(a=>({...a,[k]:e.target.value}))}/></label>)}{value.daily_fields.includes('help')&&<label className="flex gap-2 min-h-11 items-center"><input type="checkbox" checked={help} onChange={e=>setHelp(e.target.checked)}/>Quiero que mi nutricionista me contacte</label>}{value.daily_fields.includes('notes')&&<label className="block form-label">Comentario opcional<textarea className="form-control" maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)}/></label>}{error&&<p role="alert">{error}</p>}<Button disabled={busy}>Enviar respuesta</Button></form></Dialog>;
}

function ListEditor({value,org,onClose,onSaved}:{value:DailyList|'new';org:string;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const previous=value==='new'?undefined:value;const [title,setTitle]=useState(previous?.title??'');const [days,setDays]=useState(previous?.duration_days??7);const [text,setText]=useState(previous?.items.map(i=>i.text).join('\n')??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <Dialog isOpen onClose={()=>{if(!busy)onClose();}} title="Lista de próximos pasos" description="Una tarea por renglón. Cambiar el texto crea una tarea nueva sin heredar checks ni comentarios."><form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const used=new Set<string>();const items=text.split('\n').map(t=>t.trim()).filter(Boolean).map(t=>{const old=previous?.items.find(i=>i.text===t&&!used.has(i.id));const id=old?.id??crypto.randomUUID();used.add(id);return{id,text:t};});await saveList(previous?.organization_id??org,title,days,items,previous);await onSaved();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label className="block form-label">Título<input className="form-control" required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block form-label">Días<select className="form-control" value={days} onChange={e=>setDays(Number(e.target.value))}>{Array.from({length:9},(_,i)=>i+7).map(n=><option key={n}>{n}</option>)}</select></label><label className="block form-label">Tareas<textarea className="form-control" rows={6} required value={text} onChange={e=>setText(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<Button disabled={busy}>Guardar lista</Button></form></Dialog>;
}
function PhraseEditor({value,org,onClose,onSaved}:{value:DailyPhrase|'new';org:string;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const previous=value==='new'?undefined:value;const [text,setText]=useState(previous?.text??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <Dialog isOpen onClose={()=>{if(!busy)onClose();}} title="Frase motivacional" description="Si ya está aplicada, el cambio también será visible para esos pacientes."><form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await savePhrase(previous?.organization_id??org,text,previous);await onSaved();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label className="block form-label">Mensaje<textarea required maxLength={280} rows={4} className="form-control" value={text} onChange={e=>setText(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<Button disabled={busy}>Guardar frase</Button></form></Dialog>;
}
export function CheckinSettings({org}:{org:string}) {return <CheckinQuestionLibrary org={org}/>;}
