import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Activity, ArrowLeft, Building2, CalendarDays, CreditCard, Database, History, RefreshCw, ShieldCheck, Stethoscope, Users } from 'lucide-react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import type { RealAdminOrganizationDetail } from '../../../data/admin-organization-detail.types';
import type { AdminPlatformBillingCycle } from '../../../data/admin-platform-revenue.types';
import { loadRealAdminOrganizationDetail, updateRealAdminOrganizationStatus } from '../../../data/supabase/admin-organization-detail.repository';
import { RealAdminSubscriptionPanel } from './RealAdminSubscriptionPanel';

type LoadState = { status: 'loading' } | { status: 'error' } | { status: 'missing' } | { status: 'success'; detail: RealAdminOrganizationDetail };

export function RealAdminOrganizationDetailPage({ loadDetail = loadRealAdminOrganizationDetail }: { loadDetail?: (organizationId: string) => Promise<RealAdminOrganizationDetail | null> }) {
  const { organizationId = '' } = useParams();
  const [attempt, setAttempt] = useState(0);
  const [state, setState] = useState<LoadState>({ status: 'loading' });
  const [revenuePeriod, setRevenuePeriod] = useState<'monthly' | 'yearly'>('monthly');
  const [statusBusy, setStatusBusy] = useState(false);
  const [statusError, setStatusError] = useState('');

  useEffect(() => {
    let active = true;
    setState({ status: 'loading' });
    void loadDetail(organizationId).then(detail => active && setState(detail ? { status: 'success', detail } : { status: 'missing' }))
      .catch(() => active && setState({ status: 'error' }));
    return () => { active = false; };
  }, [attempt, loadDetail, organizationId]);

  const detail = state.status === 'success' ? state.detail : null;
  const billingCycles = useMemo(() => detail?.billingCycles.filter(cycle => cycle.frequency === revenuePeriod) ?? [], [detail, revenuePeriod]);

  if (state.status === 'loading') return <div className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8"><div role="status" className="rounded-2xl border border-border-subtle bg-surface p-8 text-sm text-text-secondary">Cargando detalle administrativo…</div></div>;
  if (state.status === 'missing') return <div className="mx-auto max-w-3xl space-y-4 p-4 sm:p-6 lg:p-8"><Link to="/admin/organizations" className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-brand-strong"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Volver a consultorios</Link><section className="rounded-2xl border border-border-subtle bg-surface p-8"><h2 className="text-xl font-bold text-text-primary">Consultorio no disponible</h2><p className="mt-2 text-sm text-text-secondary">No existe o tu sesión no tiene acceso al detalle administrativo solicitado.</p></section></div>;
  if (state.status === 'error') return <div className="mx-auto max-w-3xl space-y-4 p-4 sm:p-6 lg:p-8"><Link to="/admin/organizations" className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-brand-strong"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Volver a consultorios</Link><section role="alert" className="rounded-2xl border border-[#F8C4C1] bg-[#FCEBEA] p-5"><h2 className="font-semibold text-[#902A24]">No pudimos cargar la información</h2><p className="mt-1 text-sm text-text-secondary">No se modificó ningún dato. Verificá la conexión e intentá nuevamente.</p><Button type="button" variant="secondary" className="mt-4" onClick={() => setAttempt(value => value + 1)}>Reintentar</Button></section></div>;

  const { organization, usage, professionals, revenue, receipts, recentAudit } = state.detail;
  const totalProfessionals = state.detail.subscription ? state.detail.subscription.includedProfessionals + state.detail.subscription.extraProfessionals : usage.professionalCapacity;
  const changeStatus = async () => {
    const next = organization.status === 'active' ? 'suspended' : 'active';
    const verb = next === 'suspended' ? 'suspender el acceso operativo' : 'reactivar el acceso operativo';
    if (!window.confirm(`¿Confirmás ${verb} de ${organization.name}? Esta acción no elimina información clínica ni comercial.`)) return;
    setStatusBusy(true); setStatusError('');
    try { await updateRealAdminOrganizationStatus(organization.id, next); setAttempt(value => value + 1); }
    catch (error) { setStatusError(error instanceof Error ? error.message : 'No se pudo actualizar el estado.'); }
    finally { setStatusBusy(false); }
  };
  return <div className="mx-auto max-w-[1440px] space-y-6 p-4 sm:p-6 lg:p-8">
    <nav aria-label="Migas de pan" className="flex flex-wrap items-center gap-2 text-xs text-text-secondary"><Link to="/admin/organizations" className="rounded font-semibold text-brand-strong hover:underline focus-visible:outline focus-visible:outline-2">Consultorios</Link><span aria-hidden="true">/</span><span className="font-semibold text-text-primary">{organization.name}</span></nav>
    <header className="rounded-3xl border border-border-subtle bg-[linear-gradient(135deg,#E9F8F7_0%,#EEF7FB_58%,#FCF9E8_100%)] p-5 shadow-sm sm:p-7">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-white bg-white/80 text-brand-strong"><Building2 className="h-6 w-6" aria-hidden="true" /></div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-strong">Ficha administrativa REAL</p><div className="mt-1 flex flex-wrap items-center gap-2"><h2 className="break-words text-2xl font-bold text-text-primary sm:text-3xl">{organization.name}</h2><Badge variant={organization.status === 'active' ? 'active' : 'suspended'}>{organization.status === 'active' ? 'Activo' : 'Suspendido'}</Badge></div><p className="mt-1 break-all text-sm text-text-secondary">{organization.slug}</p><p className="mt-2 text-xs text-text-tertiary">Alta {formatDateTime(organization.createdAt)} · Actualizado {formatDateTime(organization.updatedAt)}</p></div></div><div className="flex flex-wrap gap-2"><Button asChild type="button" variant="secondary"><Link to="/admin/organizations"><ArrowLeft className="mr-2 h-4 w-4" aria-hidden="true" />Directorio</Link></Button><Button type="button" variant={organization.status === 'active' ? 'destructive' : 'secondary'} disabled={statusBusy} onClick={() => void changeStatus()}>{statusBusy ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" /> : null}{organization.status === 'active' ? 'Suspender consultorio' : 'Reactivar consultorio'}</Button><Button asChild type="button"><Link to="/admin/usage">Reportes y facturación</Link></Button></div></div>
      {statusError && <p role="alert" className="mt-4 rounded-xl border border-[#F8C4C1] bg-[#FCEBEA] p-3 text-sm text-[#902A24]">{statusError}</p>}
    </header>

    <section aria-label="Resumen del consultorio" className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Summary icon={CreditCard} label="Plan comercial" value={revenue.currentPlan?.toUpperCase() ?? 'Sin plan'} note={usage.subscriptionStatus ? subscriptionLabel(usage.subscriptionStatus) : 'Suscripción sin configurar'} />
      <Summary icon={Users} label="Pacientes activos" value={usage.activePatients.toLocaleString('es-AR')} note={usage.maxActivePatients === null ? 'Sin límite comercial' : `Límite ${usage.maxActivePatients.toLocaleString('es-AR')}`} />
      <Summary icon={Stethoscope} label="Miembros activos" value={usage.activeProfessionals.toLocaleString('es-AR')} note={`${totalProfessionals ? `Capacidad comercial ${totalProfessionals}` : 'Capacidad sin configurar'} · nutricionistas y responsables`} />
      <Summary icon={Database} label="PDF almacenados" value={formatBytes(usage.storedPdfBytes)} note={`Límite comercial ${usage.planStorageLimitBytes === null ? 'sin configurar' : formatBytes(usage.planStorageLimitBytes)}`} />
    </section>

    <section className="grid grid-cols-1 gap-4 xl:grid-cols-2">
      <article className="rounded-2xl border border-border-subtle bg-surface p-5 shadow-sm"><header className="flex items-start gap-3"><div className="rounded-xl bg-brand-soft p-2 text-brand-strong"><Activity className="h-5 w-5" aria-hidden="true" /></div><div><h3 className="font-bold text-text-primary">Consumo y capacidades</h3><p className="mt-1 text-xs text-text-secondary">Capacidad vigente del plan; no es un historial de períodos.</p></div></header>{usage.professionalCapacity !== null && usage.activeProfessionals > usage.professionalCapacity && <p role="status" className="mt-4 rounded-xl border border-[#F4E3B4] bg-[#FDF6E2] p-3 text-xs leading-5 text-[#70470C]">El conteo agregado de miembros supera la capacidad configurada del plan ({usage.activeProfessionals} / {usage.professionalCapacity}). Revisá los límites en Reportes; no se elimina ni bloquea información desde esta pantalla.</p>}<dl className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2"><Metric label="Pacientes activos" value={`${usage.activePatients} / ${limit(usage.maxActivePatients)}`} /><Metric label="Miembros activos (nutricionistas y responsables)" value={`${usage.activeProfessionals} / ${limit(usage.professionalCapacity)}`} /><Metric label="PDF en biblioteca" value={`${formatBytes(usage.storedPdfBytes)} / ${limitBytes(usage.planStorageLimitBytes)}`} /><Metric label="Cuota técnica individual PDF" value={`${formatBytes(usage.effectiveLibraryQuotaBytes)} agregados · ${usage.uploadEnabledProfessionals} habilitados`} /><Metric label="Asignaciones activas de planes" value={usage.activeMealPlanAssignments.toLocaleString('es-AR')} /><Metric label="Calendarios Google conectados" value={usage.connectedGoogleCalendars.toLocaleString('es-AR')} /><Metric label="Marca CUSTOM" value={`${usage.brandingAssetsCount} imágenes · ${usage.brandingSettingsFieldsCount} ajustes`} /><Metric label="Profesionales cerca/sobre cuota PDF" value={`${usage.professionalsNearLibraryQuota} / ${usage.professionalsOverLibraryQuota}`} /></dl><Link className="mt-4 inline-flex min-h-10 items-center font-semibold text-brand-strong hover:underline" to="/admin/usage">Abrir reporte detallado de uso →</Link></article>
      <article className="rounded-2xl border border-border-subtle bg-surface p-5 shadow-sm"><header className="flex items-start gap-3"><div className="rounded-xl bg-brand-soft p-2 text-brand-strong"><CalendarDays className="h-5 w-5" aria-hidden="true" /></div><div><h3 className="font-bold text-text-primary">Actividad operativa</h3><p className="mt-1 text-xs text-text-secondary">Últimos 12 meses · exclusivamente conteos agregados.</p></div></header><dl className="mt-4 grid grid-cols-2 gap-3"><Metric label="Citas" value={usage.appointmentsInPeriod.toLocaleString('es-AR')} /><Metric label="Completadas" value={usage.completedAppointmentsInPeriod.toLocaleString('es-AR')} /><Metric label="Respuestas de check-in" value={usage.checkinResponsesInPeriod.toLocaleString('es-AR')} /><Metric label="Versiones de plan publicadas" value={usage.publishedMealPlanVersionsInPeriod.toLocaleString('es-AR')} /></dl><p className="mt-4 text-[11px] leading-5 text-text-tertiary">Estos números no incluyen identidades de pacientes, respuestas, notas ni contenido clínico.</p></article>
    </section>

    <RealAdminSubscriptionPanel organizationId={organization.id} subscription={state.detail.subscription} onChanged={() => setAttempt(value => value + 1)} />

      <section className="rounded-2xl border border-border-subtle bg-surface shadow-sm"><header className="flex flex-col gap-3 border-b border-border-subtle p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="flex items-center gap-2 font-bold text-text-primary"><Stethoscope className="h-5 w-5 text-brand-strong" aria-hidden="true" />Profesionales del consultorio</h3><p className="mt-1 text-xs text-text-secondary">Identidad profesional básica y estado de membresía. El conteo es agregado; no hay nombres ni fichas de pacientes.</p></div><Button asChild type="button" variant="secondary"><Link to="/admin/nutritionists">Gestionar profesionales</Link></Button></header>
      {professionals.length ? <div className="divide-y divide-border-subtle">{professionals.map(professional => <article key={professional.userId} className="grid gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><h4 className="truncate text-sm font-semibold text-text-primary">{professional.fullName}</h4><a className="break-all text-xs text-brand-strong hover:underline" href={`mailto:${professional.email}`}>{professional.email}</a><p className="mt-1 text-[11px] text-text-tertiary">Vinculado {formatDateTime(professional.createdAt)} · {professional.assignedPatientCount} asignaciones activas agregadas</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={professional.membershipStatus === 'active' ? 'active' : 'suspended'}>{professional.membershipStatus === 'active' ? 'Membresía activa' : 'Membresía suspendida'}</Badge>{professional.accountSuspended && <Badge variant="high">Cuenta bloqueada</Badge>}</div></article>)}</div> : <p className="p-5 text-sm text-text-secondary">No hay membresías profesionales registradas.</p>}
    </section>

    <section className="rounded-2xl border border-border-subtle bg-surface p-5 shadow-sm"><header><h3 className="flex items-center gap-2 font-bold text-text-primary"><CreditCard className="h-5 w-5 text-brand-strong" aria-hidden="true" />Cuenta comercial de Nutrify</h3><p className="mt-1 text-xs text-text-secondary">Tarifas acordadas, vencimientos y cobros registrados manualmente. No procesa pagos ni genera facturas fiscales.</p></header>
      <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric label="Tarifa vigente/programada" value={revenue.termAmount === null ? 'Pendiente de configurar' : `${formatMoney(revenue.termAmount, revenue.termCurrency ?? 'ARS')} / ${revenue.billingFrequency === 'yearly' ? 'año' : 'mes'}`} /><Metric label="Condición" value={`${revenue.termPlan?.toUpperCase() ?? '—'} · ${revenue.effectiveFrom ? `${revenue.effectiveFrom > todayDate() ? 'Programada' : 'Desde'} ${formatDate(revenue.effectiveFrom)}` : 'sin vigencia'}`} /><Metric label="Historial de tarifas" value={`${revenue.termHistory.length} versiones`} /></div>
      {revenue.termHistory.length > 0 && <div className="mt-4 overflow-x-auto rounded-xl border border-border-subtle"><table className="w-full min-w-[650px] border-collapse text-left text-xs"><thead className="bg-surface-subtle"><tr><th className="table-cell-admin">Plan</th><th className="table-cell-admin">Tarifa</th><th className="table-cell-admin">Vigencia</th><th className="table-cell-admin">Estado</th></tr></thead><tbody className="divide-y divide-border-subtle">{revenue.termHistory.map(term => <tr key={term.termId}><td className="table-cell-admin font-semibold">{term.plan.toUpperCase()} · {term.billingFrequency === 'yearly' ? 'anual' : 'mensual'}</td><td className="table-cell-admin">{formatMoney(term.amount, term.currency)}</td><td className="table-cell-admin">{formatDate(term.effectiveFrom)} – {term.effectiveTo ? formatDate(term.effectiveTo) : 'abierta'}</td><td className="table-cell-admin">{term.cancelledAt ? 'Programación cancelada' : term.effectiveFrom > todayDate() ? 'Programada' : term.effectiveTo ? 'Histórica' : 'Vigente'}</td></tr>)}</tbody></table></div>}
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2" role="group" aria-label="Frecuencia de ciclos comerciales">{(['monthly', 'yearly'] as const).map(frequency => <button key={frequency} type="button" aria-pressed={revenuePeriod === frequency} onClick={() => setRevenuePeriod(frequency)} className={`min-h-10 rounded-xl border px-3 text-xs font-semibold ${revenuePeriod === frequency ? 'border-brand-strong bg-brand-soft text-brand-strong' : 'border-border-subtle text-text-secondary'}`}>{frequency === 'monthly' ? 'Ciclos mensuales' : 'Ciclos anuales'}</button>)}</div><Link className="inline-flex min-h-10 items-center font-semibold text-brand-strong hover:underline" to="/admin/usage">Administrar tarifa, registrar cobros o dar prórroga →</Link></div>
      {billingCycles.length ? <div className="mt-3 overflow-x-auto rounded-xl border border-border-subtle"><table className="w-full min-w-[850px] border-collapse text-left text-xs"><thead className="bg-surface-subtle"><tr><th className="table-cell-admin">Período</th><th className="table-cell-admin">Vencimiento</th><th className="table-cell-admin">Esperado</th><th className="table-cell-admin">Recibido</th><th className="table-cell-admin">Saldo</th><th className="table-cell-admin">Estado</th></tr></thead><tbody className="divide-y divide-border-subtle">{billingCycles.map(cycle => <BillingRow cycle={cycle} key={`${cycle.termId}:${cycle.periodStart}`} />)}</tbody></table></div> : <p className="mt-4 rounded-xl bg-surface-subtle p-4 text-sm text-text-secondary">No hay ciclos de esta frecuencia en los últimos 12 meses.</p>}
      <h4 className="mt-5 text-sm font-semibold text-text-primary">Cobros registrados en los últimos 12 meses</h4>{receipts.length ? <div className="mt-2 overflow-x-auto rounded-xl border border-border-subtle"><table className="w-full min-w-[620px] border-collapse text-left text-xs"><thead className="bg-surface-subtle"><tr><th className="table-cell-admin">Recibido</th><th className="table-cell-admin">Período cubierto</th><th className="table-cell-admin">Importe</th><th className="table-cell-admin">Estado</th></tr></thead><tbody className="divide-y divide-border-subtle">{receipts.map(receipt => <tr key={receipt.receiptId}><td className="table-cell-admin">{formatDate(receipt.receivedOn)}</td><td className="table-cell-admin">{formatDate(receipt.periodStart)} – {formatDate(receipt.periodEnd)}</td><td className="table-cell-admin font-semibold">{formatMoney(receipt.amount, receipt.currency)}</td><td className="table-cell-admin">{receipt.status === 'received' ? 'Recibido' : 'Anulado'}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-text-secondary">No hay cobros registrados en los últimos 12 meses.</p>}
    </section>

    <section className="rounded-2xl border border-border-subtle bg-surface p-5 shadow-sm"><header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="flex items-center gap-2 font-bold text-text-primary"><History className="h-5 w-5 text-brand-strong" aria-hidden="true" />Actividad administrativa reciente</h3><p className="mt-1 text-xs text-text-secondary">Últimos cambios de plataforma relacionados con este consultorio. El actor se muestra como Platform Admin.</p></div><Button asChild type="button" variant="secondary"><Link to={`/admin/audit?query=${encodeURIComponent(organization.slug)}`}>Ver auditoría completa</Link></Button></header>
      {recentAudit.length ? <ol className="mt-4 divide-y divide-border-subtle">{recentAudit.map(event => <li key={event.eventId} className="flex flex-col gap-1 py-3 sm:flex-row sm:items-center sm:justify-between sm:gap-4"><div className="min-w-0"><p className="text-sm font-semibold text-text-primary">{auditLabel(event.eventType)}{event.previousValue !== null ? ` · ${auditValue(event.previousValue)} → ${auditValue(event.newValue)}` : ''}</p><p className="mt-1 text-[11px] text-text-tertiary">Platform Admin · {formatDateTime(event.occurredAt)}</p></div></li>)}</ol> : <p className="mt-4 rounded-xl bg-surface-subtle p-4 text-sm text-text-secondary">No hay acciones administrativas registradas para este consultorio durante el período consultado.</p>}
    </section>

    <aside className="flex gap-3 rounded-2xl border border-[#C6D4F8] bg-[#EAEFFC] p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#2D3F99]" aria-hidden="true" /><p className="text-xs leading-5 text-text-secondary"><strong className="text-[#2D3F99]">Privacidad:</strong> esta ficha expone datos administrativos y comerciales del consultorio y métricas agregadas. No permite abrir pacientes ni acceder a respuestas, notas, mediciones, planes o archivos individuales. Los cambios se realizan desde las superficies administrativas existentes y quedan sujetos a sus controles y auditoría.</p></aside>
  </div>;
}

function BillingRow({ cycle }: { cycle: AdminPlatformBillingCycle }) {
  const status = cycle.paymentStatus === 'paid' ? 'Pagado' : cycle.dueStatus === 'overdue' ? 'Vencido' : cycle.dueStatus === 'grace' ? 'En gracia manual' : cycle.paymentStatus === 'partial' ? 'Parcial' : cycle.dueStatus === 'due_today' ? 'Vence hoy' : 'Pendiente';
  const variant = cycle.dueStatus === 'overdue' ? 'high' : cycle.dueStatus === 'grace' || cycle.paymentStatus === 'partial' ? 'medium' : cycle.paymentStatus === 'paid' ? 'active' : 'neutral';
  return <tr><td className="table-cell-admin">{formatDate(cycle.periodStart)} – {formatDate(cycle.periodEnd)}</td><td className="table-cell-admin">{formatDate(cycle.dueDate)}{cycle.extensionCount > 0 && <span className="mt-1 block text-[10px] text-text-tertiary">{cycle.extensionCount} prórroga(s) manual(es)</span>}</td><td className="table-cell-admin">{formatMoney(cycle.expectedAmount, cycle.currency)}</td><td className="table-cell-admin">{formatMoney(cycle.receivedAmount, cycle.currency)}</td><td className="table-cell-admin font-semibold">{formatMoney(cycle.balance, cycle.currency)}</td><td className="table-cell-admin"><Badge variant={variant}>{status}</Badge></td></tr>;
}

function Summary({ icon: Icon, label, value, note }: { icon: typeof Users; label: string; value: string; note: string }) { return <article className="rounded-2xl border border-border-subtle bg-surface p-4 shadow-sm"><div className="flex items-center gap-2 text-brand-strong"><Icon className="h-4 w-4" aria-hidden="true" /><p className="text-xs font-semibold text-text-secondary">{label}</p></div><p className="mt-3 break-words text-2xl font-bold text-text-primary">{value}</p><p className="mt-1 text-[11px] text-text-tertiary">{note}</p></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-border-subtle bg-surface-subtle p-3"><dt className="text-[11px] text-text-secondary">{label}</dt><dd className="mt-1 break-words text-sm font-bold text-text-primary">{value}</dd></div>; }
function limit(value: number | null) { return value === null ? 'sin límite comercial' : value.toLocaleString('es-AR'); }
function limitBytes(value: number | null) { return value === null ? 'sin límite comercial' : formatBytes(value); }
function formatBytes(value: number) { if (!value) return '0 MB'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const index = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); return `${(value / 1024 ** index).toLocaleString('es-AR', { maximumFractionDigits: index >= 2 ? 1 : 0 })} ${units[index]}`; }
function formatMoney(amount: number, currency: string) { try { return new Intl.NumberFormat('es-AR', { style: 'currency', currency, maximumFractionDigits: 2 }).format(amount); } catch { return `${amount.toLocaleString('es-AR')} ${currency}`; } }
function formatDate(value: string) { return new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(`${value.slice(0, 10)}T00:00:00Z`)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function todayDate() { return new Date().toISOString().slice(0, 10); }
function subscriptionLabel(status: NonNullable<RealAdminOrganizationDetail['usage']['subscriptionStatus']>) { return ({ trialing: 'En prueba', active: 'Activa', grace: 'En gracia', suspended: 'Suspendida', cancelled: 'Cancelada' })[status]; }
function auditLabel(type: RealAdminOrganizationDetail['recentAudit'][number]['eventType']) { return ({ organization_created: 'Alta de consultorio', organization_status_changed: 'Cambio de estado operativo', subscription_changed: 'Cambio de plan', professional_membership_changed: 'Cambio de membresía profesional', professional_account_suspension_changed: 'Bloqueo global de cuenta' })[type]; }
function auditValue(value: string) {
  const labels: Record<string, string> = { active: 'Activo', inactive: 'Inactivo', suspended: 'Suspendido', trialing: 'En prueba', grace: 'En gracia', cancelled: 'Cancelado' };
  return value.split(' · ').map(part => labels[part] ?? part.toUpperCase()).join(' · ');
}
