/* eslint-disable jsx-a11y/no-autofocus */
import { ClipboardList } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { loadMealPlanActivity, loadPatientMealPlans, setMealPlanActivity } from '../../../data/supabase/clinical-meal-plans.repository';
import type { ClinicalMealPlanDay, ClinicalMealPlanMeal, MealPlanAdherenceStatus, RealMealPlanActivity, RealPatientMealPlan } from '../../../data/clinical-meal-plans.types';

function Meal({ plan, day, meal, activity, refresh }: { plan: RealPatientMealPlan; day: ClinicalMealPlanDay; meal: ClinicalMealPlanMeal; activity?: RealMealPlanActivity; refresh: () => Promise<void> }) {
  const [comment, setComment] = useState(activity?.patientComment ?? '');
  const [commentOpen,setCommentOpen]=useState(Boolean(activity?.patientComment));
  const status=activity?.adherenceStatus;
  useEffect(() => setComment(activity?.patientComment ?? ''), [activity?.patientComment]);
  const save = async (nextStatus:MealPlanAdherenceStatus|undefined=status,nextComment=comment) => { await setMealPlanActivity({ mealPlanId:plan.id,dayId:day.id,mealId:meal.id,adherenceStatus:nextStatus,comment:nextComment });await refresh(); };
  const choices:[MealPlanAdherenceStatus,string][]=[['completed','Cumplida'],['partial','Parcial'],['not_completed','No cumplida']];
  return <div className={`rounded-xl border p-3 ${status==='completed'?'border-semantic-success bg-semantic-success-bg':status==='partial'?'border-semantic-warning bg-semantic-warning-bg':status==='not_completed'?'border-semantic-critical/30 bg-semantic-critical-bg':'border-border-subtle bg-surface'}`}><div><strong className={status==='completed'?'text-text-secondary line-through':'text-text-primary'}>{meal.type}</strong>{meal.items.map(item => <span className="mt-1 block text-xs text-text-secondary" key={item.id}>{item.description}{item.quantity ? ` · ${item.quantity}` : ''}</span>)}</div><fieldset className="mt-3"><legend className="sr-only">Cumplimiento de {meal.type}</legend><div className="grid grid-cols-3 gap-1">{choices.map(([value,label])=><button type="button" key={value} aria-pressed={status===value} className={`min-h-10 rounded-lg px-1 text-[11px] font-semibold ${status===value?'bg-brand-strong text-white':'border border-border-subtle bg-surface text-text-secondary'}`} onClick={()=>void save(status===value?undefined:value)}>{label}</button>)}</div></fieldset>{meal.items.filter(item=>item.recipeId).map(item=><Link key={item.id} className="min-h-11 flex items-center text-sm text-brand-strong" to={`/patient/recipes/${item.recipeId}`}>Ver receta de {item.description}</Link>)}{!commentOpen?<Button size="sm" variant="ghost" className="mt-1" onClick={()=>setCommentOpen(true)}>{activity?.patientComment?'Ver comentario':'Agregar comentario'}</Button>:<div className="mt-2"><textarea autoFocus className="form-control min-h-18 text-xs" maxLength={500} value={comment} onChange={event => setComment(event.target.value)} placeholder="Comentario opcional para tu nutricionista" /><div className="mt-2 flex flex-wrap justify-end gap-2"><Button size="sm" variant="ghost" onClick={()=>{setComment(activity?.patientComment??'');setCommentOpen(false);}}>Cerrar</Button><Button size="sm" variant="secondary" onClick={() => void save(status)} disabled={comment === (activity?.patientComment ?? '')}>Guardar comentario</Button></div></div>}</div>;
}

export function RealPatientMealPlansPage() {
  const [plans, setPlans] = useState<RealPatientMealPlan[]>([]); const [activity, setActivity] = useState<RealMealPlanActivity[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refresh = async () => { setLoading(true); setError(null); try { const nextPlans = await loadPatientMealPlans(); setPlans(nextPlans); setActivity((await Promise.all(nextPlans.map(plan => loadMealPlanActivity(plan.id)))).flat()); } catch { setError('No pudimos cargar tu plan. Intentá nuevamente.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const activityFor = (planId: string, dayId: string, mealId: string) => activity.find(item => item.mealPlanId === planId && item.dayId === dayId && item.mealId === mealId);
  if (loading) return <div className="mx-auto max-w-md p-4"><p role="status" className="text-sm text-text-secondary">Cargando tu plan…</p></div>;
  if (error) return <div className="mx-auto max-w-md p-4"><Card><p className="text-sm text-semantic-critical">{error}</p><Button className="mt-4" variant="secondary" onClick={() => void refresh()}>Reintentar</Button></Card></div>;
  return <div className="mx-auto max-w-md space-y-5 p-4 pb-10"><Card><Button asChild><Link to="/patient/check-in/free">Completar check-in</Link></Button><p className="text-sm text-text-secondary mt-2">Cuando lo necesites, sin frecuencia fija.</p></Card><div className="flex items-center gap-2"><ClipboardList className="h-6 w-6 text-brand-strong" /><div><h1 className="text-2xl font-bold">Tu plan alimentario</h1><p className="text-sm text-text-secondary">Marcá cada comida y comentá sólo cuando lo necesites.</p></div></div>{plans.length === 0 ? <Card className="py-12 text-center"><h2 className="text-lg font-bold">Todavía no tenés un plan activo</h2><p className="mt-2 text-sm text-text-secondary">Tu nutricionista te avisará cuando publique uno.</p></Card> : plans.map(plan => <Card key={plan.id} className="space-y-3"><h2 className="text-lg font-bold">{plan.title}</h2>{plan.content.days.map((day, index) => {const completed=day.meals.filter(meal=>activityFor(plan.id,day.id,meal.id)?.adherenceStatus==='completed').length;return <details key={day.id} open={index === 0} className="rounded-xl border border-border-subtle bg-surface-subtle p-3"><summary className="cursor-pointer list-none text-sm font-bold"><span className="flex min-h-11 items-center justify-between gap-3"><span>Día {index + 1}{day.title ? ` · ${day.title}` : ''}</span><span className="text-xs font-semibold text-brand-strong">{completed}/{day.meals.length}</span></span></summary><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-border-subtle"><div className="h-full rounded-full bg-brand-strong" style={{width:`${day.meals.length?completed/day.meals.length*100:0}%`}}/></div><div className="mt-3 space-y-2">{day.meals.map(meal => <Meal key={meal.id} plan={plan} day={day} meal={meal} activity={activityFor(plan.id, day.id, meal.id)} refresh={refresh} />)}</div></details>;})}</Card>)}</div>;
}
