import {CalendarDays,CheckCircle2,Clock3,MapPin,Video} from 'lucide-react';
import {useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {getSupabaseClient} from '../../../auth/supabase-client';
import {Button} from '../../../components/ui/Button';
import {Card} from '../../../components/ui/Card';

type Slot={starts_at:string;ends_at:string;modality_virtual:boolean;modality_in_person:boolean};
const label=new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'});
const time=new Intl.DateTimeFormat('es-AR',{hour:'2-digit',minute:'2-digit',hour12:false});
export function RealPatientAppointmentRequestPage(){
 const [duration,setDuration]=useState(45),[modality,setModality]=useState<'virtual'|'in_person'>('virtual'),[slots,setSlots]=useState<Slot[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const {data,error:e}=await getSupabaseClient().schema('api').rpc('get_patient_appointment_slots',{p_duration_minutes:duration});if(e)setError(e.message);else setSlots((data??[]) as Slot[]);setLoading(false);setSelected('');},[duration]);
 useEffect(()=>{void load();},[load]);
 const submit=async()=>{if(!selected)return;setSaving(true);setError('');const {error:e}=await getSupabaseClient().schema('api').rpc('request_patient_appointment',{p_starts_at:selected,p_duration_minutes:duration,p_modality:modality});if(e)setError(e.message);else setSent(true);setSaving(false);};
 if(sent)return <main className="mx-auto max-w-lg p-4 sm:p-8"><Card className="space-y-4 py-10 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-success"/><h1 className="text-xl font-bold">Solicitud enviada</h1><p className="text-sm text-text-secondary">Tu profesional debe confirmarla. La cita no queda agendada automáticamente.</p><Button asChild className="w-full"><Link to="/patient/appointments">Ver mis citas</Link></Button></Card></main>;
 return <main className="mx-auto max-w-2xl space-y-5 p-4 sm:p-8"><Link className="text-sm font-semibold text-brand-strong" to="/patient">← Volver al inicio</Link><div><div className="flex items-center gap-2"><CalendarDays className="h-6 w-6 text-brand-strong"/><h1 className="text-2xl font-bold">Solicitar una cita</h1></div><p className="mt-1 text-sm text-text-secondary">Tus datos ya están registrados en tu ficha. Sólo elegí duración, modalidad y horario.</p></div><Card className="space-y-5">{error&&<p role="alert" className="rounded-xl bg-critical/10 p-3 text-sm text-critical">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><label className="form-label">Duración<select className="form-control" value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[15,30,45,60,75,90].map(v=><option key={v} value={v}>{v} minutos</option>)}</select></label><div><p className="form-label">Modalidad</p><div className="grid grid-cols-2 gap-2"><button type="button" className={`rounded-xl border p-2 text-xs ${modality==='virtual'?'border-brand-strong bg-brand-soft':''}`} onClick={()=>setModality('virtual')}><Video className="mr-1 inline h-4 w-4"/>Virtual</button><button type="button" className={`rounded-xl border p-2 text-xs ${modality==='in_person'?'border-brand-strong bg-brand-soft':''}`} onClick={()=>setModality('in_person')}><MapPin className="mr-1 inline h-4 w-4"/>Presencial</button></div></div></div><h2 className="font-bold">Horarios disponibles</h2>{loading?<p role="status">Buscando disponibilidad…</p>:slots.length===0?<p className="rounded-xl bg-surface-subtle p-5 text-sm text-text-secondary">No hay horarios disponibles con esta duración.</p>:<div className="grid gap-2 sm:grid-cols-2">{slots.slice(0,30).map(slot=><button key={slot.starts_at} type="button" onClick={()=>setSelected(slot.starts_at)} className={`rounded-xl border p-3 text-left ${selected===slot.starts_at?'border-brand-strong bg-brand-soft':'border-border-subtle'}`}><span className="block text-xs capitalize">{label.format(new Date(slot.starts_at))}</span><span className="mt-1 inline-flex items-center gap-1 font-bold text-brand-strong"><Clock3 className="h-4 w-4"/>{time.format(new Date(slot.starts_at))}</span></button>)}</div>}<p className="text-xs text-text-secondary">La disponibilidad considera horarios, pausas, bloqueos, citas existentes y ocupación de Google Calendar.</p><Button className="w-full" disabled={!selected||saving} onClick={()=>void submit()}>{saving?'Enviando…':'Enviar solicitud'}</Button></Card></main>;
}
