import {useEffect,useState} from 'react';
import {BellRing,Plus,ArrowUp,ArrowDown} from 'lucide-react';
import {z} from 'zod';
import {getSupabaseClient} from '../../auth/supabase-client';
import {questionSchema,newQuestion,suggestions,type CheckinQuestion} from '../../lib/checkinQuestions';
import {Card} from '../ui/Card';
import {Button} from '../ui/Button';

export function CheckinQuestionLibrary({org}:{org:string}) {
 const [questions,setQuestions]=useState<CheckinQuestion[]>([]),[version,setVersion]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[retry,setRetry]=useState(0),[ready,setReady]=useState(false),[archived,setArchived]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);setReady(false);setError('');setSaved(false);
 Promise.resolve(getSupabaseClient().schema('api').rpc('get_checkin_questions',{p_org:org})).then(({data,error:problem})=>{if(!active)return;if(problem)throw new Error('No pudimos cargar las preguntas.');const value=z.object({questions:z.array(questionSchema).nullable(),updated_at:z.string().nullable()}).parse(data);setQuestions(value.questions??suggestions.map(newQuestion));setVersion(value.updated_at);setReady(true);}).catch(()=>{if(active)setError('No pudimos cargar las preguntas. Reintentá.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[org,retry]);
 const count=questions.filter(q=>q.alert).length;
 function edit(index:number,patch:Partial<CheckinQuestion>,semantic=false){setSaved(false);setQuestions(rows=>rows.map((q,i)=>i===index?{...q,...patch,...(semantic?{id:crypto.randomUUID()}: {})}:q));}
 function move(index:number,delta:number){setSaved(false);setQuestions(rows=>{const copy=[...rows];[copy[index],copy[index+delta]]=[copy[index+delta]!,copy[index]!];return copy;});}
 async function save(){setBusy(true);setError('');setSaved(false);try{const {data,error:problem}=await getSupabaseClient().schema('api').rpc('save_checkin_questions',{p_org:org,p_questions:questions,p_expected:version??undefined});if(problem)throw new Error(problem.message);if(typeof data!=='string')throw new Error('No se confirmó el guardado. Recargá.');setVersion(data);setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Card className="space-y-4"><h2 className="font-bold">Preguntas del check-in general</h2><p className="text-sm text-text-secondary">Elegí, editá y ordená las preguntas para tus pacientes. Todas son opcionales de incluir. Los cambios sólo se aplican a nuevos check-ins; los enviados conservan su formulario y sus reglas.</p>
 <p className="rounded-xl bg-surface-subtle p-3 text-sm"><BellRing className="inline h-4 w-4 mr-2" aria-hidden="true"/><b>Preguntas con alerta ({count}/2).</b> Marcá hasta dos y elegí qué respuesta genera un aviso para revisar. No son diagnósticos ni avisos de emergencia. Texto libre se revisa manualmente.</p>
 {loading?<p role="status">Cargando preguntas…</p>:ready&&<fieldset disabled={busy} className="min-w-0 space-y-4">
 {!version&&<p className="text-xs text-text-secondary">Empezá con estas 3 preguntas editables o creá las tuyas. Guardá para aplicarlas a nuevos check-ins.</p>}
 <div className="flex flex-wrap items-center justify-between gap-2"><Button variant="secondary" disabled={questions.length>=100} onClick={()=>{setSaved(false);setQuestions(v=>[...v,newQuestion()]);}}><Plus className="h-4 w-4"/>Nueva pregunta</Button><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Mostrar archivadas</label></div>
 {questions.map((q,index)=>(!q.archived||archived)&&<section key={index} className="space-y-2 rounded-xl border border-border-subtle p-3">
 <div className="flex flex-wrap items-center justify-between gap-2"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" disabled={q.archived} checked={q.enabled&&!q.archived} onChange={e=>edit(index,{enabled:e.target.checked,...(!e.target.checked?{alert:null}:{})})}/>Incluir pregunta {index+1}{q.archived?' · Archivada':''}</label><div className="flex flex-wrap gap-1"><Button variant="ghost" disabled={index===0} aria-label={`Subir pregunta ${index+1}`} onClick={()=>move(index,-1)}><ArrowUp className="h-4 w-4"/></Button><Button variant="ghost" disabled={index===questions.length-1} aria-label={`Bajar pregunta ${index+1}`} onClick={()=>move(index,1)}><ArrowDown className="h-4 w-4"/></Button><Button variant="ghost" onClick={()=>edit(index,{archived:!q.archived,enabled:false,alert:null})}>{q.archived?'Restaurar':'Archivar'}</Button></div></div>
 <label className="form-label"><span className="sr-only">Pregunta {index+1}</span><textarea rows={2} disabled={q.archived} className="form-control min-h-0 resize-y" maxLength={300} value={q.text} onChange={e=>edit(index,{text:e.target.value},true)}/></label>
 <div className="flex flex-wrap gap-x-3 gap-y-1 items-center"><label className="form-label min-w-0"><span className="sr-only">Respuesta</span><select className="form-control" disabled={q.archived} value={q.type} onChange={e=>edit(index,{type:e.target.value as CheckinQuestion['type'],options:e.target.value==='choice'?['Opción 1','Opción 2']:[],alert:null},true)}><option value="scale">Escala de 1 a 5</option><option value="yesno">Sí / No</option><option value="choice">Una opción</option><option value="text">Texto breve</option></select></label><label className="flex min-h-11 gap-2 items-center text-sm"><input disabled={q.archived} type="checkbox" checked={q.required} onChange={e=>edit(index,{required:e.target.checked})}/>Respuesta obligatoria</label>
 <Button variant={q.alert?'secondary':'ghost'} aria-pressed={!!q.alert} disabled={q.archived||!q.enabled||q.type==='text'||(!q.alert&&count>=2)} onClick={()=>edit(index,{alert:q.alert?null:{op:q.type==='scale'?'lte':'in',values:q.type==='scale'?['2']:[]}})}><BellRing className="h-4 w-4"/>{q.alert?'Alerta activada':'Activar alerta'}</Button></div>
 {q.type==='choice'&&<label className="form-label">Opciones (una por línea, entre 2 y 10)<textarea disabled={q.archived} className="form-control" value={q.options.join('\n')} onChange={e=>edit(index,{options:e.target.value.split('\n'),alert:null},true)}/></label>}
 {q.type==='text'&&<p className="text-xs text-text-secondary">Sin alerta automática: el texto necesita revisión humana.</p>}
 {q.alert&&<div className="rounded-xl bg-surface-subtle p-3 space-y-2"><p className="text-sm font-semibold">Generar aviso cuando la respuesta sea:</p>{q.type==='scale'?<div className="grid grid-cols-2 gap-2"><label className="form-label">Condición<select className="form-control" value={q.alert.op} onChange={e=>edit(index,{alert:{...q.alert!,op:e.target.value as 'lte'|'gte'}})}><option value="lte">Igual o menor que</option><option value="gte">Igual o mayor que</option></select></label><label className="form-label">Valor<select className="form-control" value={q.alert.values[0]} onChange={e=>edit(index,{alert:{...q.alert!,values:[e.target.value]}})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label></div>:(q.type==='yesno'?['Sí','No']:q.options).map((option,i)=><label key={i} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={q.alert!.values.includes(option)} onChange={e=>edit(index,{alert:{op:'in',values:e.target.checked?[...q.alert!.values,option]:q.alert!.values.filter(v=>v!==option)}})}/>{option}</label>)}</div>}
 </section>)}
 <p className="text-xs text-text-secondary">Archivar retira una pregunta de la biblioteca activa, sin borrar respuestas anteriores. Podés dejar todas desactivadas, pero necesitarás al menos una para asignar un check-in.</p>
 <Button onClick={()=>void save()}>{busy?'Guardando…':'Guardar preguntas'}</Button>
 </fieldset>}{error&&<p role="alert">{error}</p>}{saved&&<p role="status">Preguntas guardadas para los próximos check-ins.</p>}<Button variant="ghost" disabled={busy||loading} onClick={()=>setRetry(v=>v+1)}>Recargar preguntas guardadas</Button>
 </Card>;
}
