import {useCallback,useEffect,useState} from 'react';
import {CalendarClock,PauseCircle,RefreshCw} from 'lucide-react';
import {z} from 'zod';
import {getSupabaseClient} from '../../auth/supabase-client';
import {Card} from '../ui/Card';
import {Button} from '../ui/Button';

const patientSchema=z.object({patient_id:z.string(),first_name:z.string(),last_name:z.string(),frequency:z.enum(['daily','weekly','paused']),configured:z.boolean(),next_run_on:z.string().nullable(),last_assigned_at:z.string().nullable(),last_skipped_on:z.string().nullable()});
const automationSchema=z.object({enabled:z.boolean(),updated_at:z.string().nullable(),patients:z.array(patientSchema)});
type Automation=z.infer<typeof automationSchema>;
const labels={daily:'Diario',weekly:'Semanal',paused:'Pausado'} as const;

export function CheckinAutomationSettings({org}:{org:string}){
 const [data,setData]=useState<Automation|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const {data:result,error:problem}=await getSupabaseClient().schema('api').rpc('get_checkin_automation',{p_org:org});if(problem)throw problem;setData(automationSchema.parse(result));}catch{setError('No pudimos cargar la automatización. Reintentá.');}finally{setLoading(false);}},[org]);
 useEffect(()=>{void load();},[load]);
 async function toggle(){if(!data)return;setBusy('global');setError('');setMessage('');try{const {data:stamp,error:problem}=await getSupabaseClient().schema('api').rpc('save_checkin_automation_global',{p_org:org,p_enabled:!data.enabled,p_expected:data.updated_at??undefined});if(problem)throw problem;setData({...data,enabled:!data.enabled,updated_at:stamp});setMessage(!data.enabled?'Automatización activada. Se ejecutará una vez por día.':'Automatización pausada para todos los pacientes.');}catch{setError('No pudimos cambiar el estado. Recargá y reintentá.');}finally{setBusy('');}}
 async function setFrequency(patientId:string,frequency:'daily'|'weekly'|'paused'){setBusy(patientId);setError('');setMessage('');try{const {error:problem}=await getSupabaseClient().schema('api').rpc('save_checkin_patient_frequency',{p_org:org,p_patient:patientId,p_frequency:frequency});if(problem)throw problem;setData(current=>current?{...current,patients:current.patients.map(patient=>patient.patient_id===patientId?{...patient,frequency,configured:true,next_run_on:frequency==='paused'?null:patient.next_run_on??new Date().toISOString().slice(0,10)}:patient)}:current);setMessage('Frecuencia guardada.');}catch{setError('No pudimos guardar la frecuencia de ese paciente.');}finally{setBusy('');}}
 return <Card className="space-y-4">
  <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-soft text-brand-strong"><CalendarClock className="h-5 w-5"/></span><div><h2 className="font-bold">Automatización</h2><p className="mt-1 text-sm text-text-secondary">El sistema revisa una vez al día a quién corresponde enviarle un check-in. No usa un horario exacto.</p></div></div>{data&&<Button variant={data.enabled?'secondary':'primary'} disabled={Boolean(busy)} onClick={()=>void toggle()}>{data.enabled?<><PauseCircle className="h-4 w-4"/>Pausar todo</>:<><CalendarClock className="h-4 w-4"/>Activar automatización</>}</Button>}</div>
  <p className="rounded-xl bg-surface-subtle p-3 text-xs text-text-secondary"><b className="text-text-primary">Sin acumulación:</b> si un paciente todavía tiene un check-in pendiente, ese ciclo se omite. La frecuencia diaria aparece como sugerencia, pero no queda configurada para un paciente hasta que la guardás.</p>
  {loading?<p role="status" className="text-sm text-text-secondary">Cargando frecuencias…</p>:data&&<div className="overflow-hidden rounded-xl border border-border-subtle">{data.patients.map(patient=><div key={patient.patient_id} className="grid gap-2 border-b border-border-subtle p-3 last:border-0 sm:grid-cols-[minmax(0,1fr)_180px] sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-semibold">{patient.first_name} {patient.last_name}</p><p className="text-xs text-text-secondary">{patient.configured?patient.frequency==='paused'?'Envíos pausados':`Configurado: ${labels[patient.frequency].toLowerCase()}`:'Sin configurar · sugerencia diaria'}</p></div><select aria-label={`Frecuencia de ${patient.first_name} ${patient.last_name}`} className="form-control" disabled={busy===patient.patient_id} value={patient.configured?patient.frequency:''} onChange={event=>{if(event.target.value)void setFrequency(patient.patient_id,event.target.value as 'daily'|'weekly'|'paused');}}><option value="">Elegir · diaria sugerida</option><option value="daily">Diario</option><option value="weekly">Semanal</option><option value="paused">Pausado</option></select></div>)}{!data.patients.length&&<p className="p-4 text-sm text-text-secondary">No hay pacientes activos asignados.</p>}</div>}
  {message&&<p role="status" className="text-sm text-brand-strong">{message}</p>}{error&&<p role="alert" className="text-sm text-critical">{error}</p>}
  <Button variant="ghost" disabled={loading||Boolean(busy)} onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Recargar configuración</Button>
 </Card>;
}
