import {useState} from 'react';
import {Download,FileUp} from 'lucide-react';
import {Dialog} from '../ui/Dialog';import {Button} from '../ui/Button';
import {mealPlanCsvTemplate,parseMealPlanCsv,type MealPlanImportResult} from '../../lib/mealPlanCsv';
import {createMealPlan} from '../../data/supabase/clinical-meal-plans.repository';
export function MealPlanImportDialog({open,organizationId,onClose,onCreated}:{open:boolean;organizationId?:string;onClose:()=>void;onCreated:(id:string)=>void}){const [title,setTitle]=useState('Plan importado'),[file,setFile]=useState<File|null>(null),[result,setResult]=useState<MealPlanImportResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const template=()=>{const url=URL.createObjectURL(new Blob([mealPlanCsvTemplate],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='plantilla-plan-alimentario.csv';link.click();URL.revokeObjectURL(url);};
 const inspect=async(selected:File|null)=>{setFile(selected);setResult(null);setError('');if(!selected)return;if(selected.size>1024*1024){setError('El CSV no puede superar 1 MB.');return;}try{setResult(parseMealPlanCsv(await selected.text()));}catch{setError('No pudimos leer el archivo CSV.');}};
 const create=async()=>{if(!organizationId||!result?.content||!title.trim())return;setBusy(true);setError('');try{onCreated(await createMealPlan(organizationId,title.trim(),result.content));}catch{setError('No pudimos crear el borrador importado. Reintentá.');}finally{setBusy(false);}};
 return <Dialog isOpen={open} onClose={()=>{if(!busy)onClose();}} title="Importar plan desde CSV" description="La importación siempre crea un borrador privado para revisión profesional."><div className="space-y-4"><Button variant="secondary" onClick={template}><Download className="h-4 w-4"/>Descargar plantilla</Button><p className="text-xs text-text-secondary">Columnas obligatorias: dia, titulo_dia, comida, alimento, cantidad y alternativas. Conservá exactamente esos encabezados.</p><label className="form-label">Título del nuevo plan<input className="form-control" maxLength={120} required value={title} onChange={event=>setTitle(event.target.value)}/></label><label className="form-label">Archivo CSV<input className="form-control" type="file" accept=".csv,text/csv" onChange={event=>void inspect(event.target.files?.[0]??null)}/></label>{file&&<p className="break-all text-xs text-text-secondary">{file.name}</p>}{result&&result.errors.length===0&&<div className="rounded-xl bg-semantic-success-bg p-3 text-sm"><b>Listo para importar.</b> {result.content!.days.length} días y {result.rows} filas válidas.</div>}{result&&result.errors.length>0&&<div className="max-h-56 overflow-auto rounded-xl bg-semantic-critical-bg p-3"><p className="text-sm font-bold text-semantic-critical">Corregí {result.errors.length} {result.errors.length===1?'problema':'problemas'} y volvé a seleccionar el archivo:</p><ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-semantic-critical">{result.errors.map(item=><li key={item}>{item}</li>)}</ul></div>}{error&&<p role="alert" className="text-sm text-critical">{error}</p>}<div className="flex justify-end gap-2 border-t border-border-subtle pt-3"><Button variant="ghost" disabled={busy} onClick={onClose}>Cancelar</Button><Button disabled={busy||!result?.content||!title.trim()} onClick={()=>void create()}><FileUp className="h-4 w-4"/>{busy?'Importando…':'Crear borrador'}</Button></div></div></Dialog>}
