import {useState} from 'react';
import {getSupabaseClient} from '../../auth/supabase-client';
import type {CheckinQuestion} from '../../lib/checkinQuestions';
import {Dialog} from '../ui/Dialog';
import {Button} from '../ui/Button';
export function QuestionCheckinForm({id,questions,onClose,onSaved,submit}:{submit?:(answers:Record<string,string>)=>Promise<void>;id:string;questions:CheckinQuestion[];onClose:()=>void;onSaved:()=>Promise<void>}) {
 const [answers,setAnswers]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog isOpen onClose={()=>{if(!busy)onClose();}} title="Tu check-in" description="Respondé las preguntas de tu profesional. Las indicadas como opcionales pueden quedar vacías."><form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{if(submit){await submit(answers);}else{const {error:problem}=await getSupabaseClient().schema('api').rpc('submit_question_checkin',{p_assignment:id,p_answers:answers});if(problem)throw new Error(problem.message);}await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><fieldset disabled={busy} className="space-y-4">{questions.map(q=><label key={q.id} className="form-label block">{q.text} <span className="font-normal">({q.required?'obligatoria':'opcional'})</span>{q.type==='text'?<textarea className="form-control" required={q.required} maxLength={500} value={answers[q.id]??''} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))}/>:<select className="form-control" required={q.required} value={answers[q.id]??''} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))}><option value="">Elegí una respuesta</option>{(q.type==='scale'?['1','2','3','4','5']:q.type==='yesno'?['Sí','No']:q.options).map(option=><option key={option}>{option}</option>)}</select>}</label>)}<Button type="submit">{busy?'Enviando…':'Enviar respuesta'}</Button></fieldset>{error&&<p role="alert">{error}</p>}</form></Dialog>;
}
