import {useEffect,useState} from 'react';
import {Card} from '../ui/Card';
import {Button} from '../ui/Button';
import {localDate} from '../../lib/anthropometry';
import {loadInitialMeasurements,saveInitialMeasurements,type InitialMeasurements} from '../../data/supabase/patient-profile.repository';
const fields=[['height_cm','Altura (cm)',300],['initial_weight_kg','Peso inicial (kg)',1000],['waist_cm','Cintura inicial (cm)',500],['hip_cm','Cadera inicial (cm)',500],['target_weight_kg','Peso objetivo (kg)',1000]] as const;
export function RealInitialMeasurements({patientId,patient=false}:{patientId:string;patient?:boolean}){
 const [row,setRow]=useState<InitialMeasurements|null>(null),[values,setValues]=useState<Record<string,string>>({}),[date,setDate]=useState(localDate()),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');loadInitialMeasurements(patientId).then(r=>{if(active){setRow(r);setDate(r?.recorded_on??localDate());setValues(Object.fromEntries(fields.map(([k])=>[k,r?.[k]===null||r?.[k]===undefined?'':String(r[k])])));}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[patientId,retry]);
 return <Card className="space-y-4"><h2 className="font-bold text-lg">Datos antropométricos iniciales</h2><p className="text-sm text-text-secondary">Opcionales. Son la referencia del perfil; no crean una revisión ni un registro cotidiano. El objetivo lo declara el paciente y no implica una recomendación clínica.</p>{loading?<p role="status">Cargando datos…</p>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setSaved(false);try{await saveInitialMeasurements(patientId,date,Object.fromEntries(fields.map(([k])=>[k,values[k]?Number(values[k]):null])),row?.updated_at);setRetry(n=>n+1);setSaved(true);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label className="block form-label">Fecha de referencia<input type="date" required max={localDate()} className="form-control" value={date} onChange={e=>{setDate(e.target.value);setSaved(false);}}/></label><div className="grid sm:grid-cols-2 gap-4">{fields.map(([key,label,max])=><label key={key} className="form-label">{label}<input type="number" min="0.1" step="0.1" max={max} disabled={!patient&&key==='target_weight_kg'} className="form-control" value={values[key]??''} onChange={e=>{setValues(v=>({...v,[key]:e.target.value}));setSaved(false);}}/></label>)}</div><Button disabled={busy||!!error}>Guardar datos iniciales</Button></form>}{error&&<div role="alert"><p>{error}</p><Button variant="secondary" onClick={()=>setRetry(n=>n+1)}>Recargar datos</Button></div>}{saved&&<p role="status">Datos iniciales guardados.</p>}</Card>;
}
