import { useEffect, useState } from 'react';
import {loadInitialMeasurements} from '../../data/supabase/patient-profile.repository';
import { Button } from '../ui/Button';
import { Card } from '../ui/Card';
import { displayMeasurementDate,localDate,measurementRange } from '../../lib/anthropometry';
import { recordWeight,type DailyWeight } from '../../data/supabase/daily-followup.repository';

export function RealDailyWeight({patientId,rows,onSaved}:{patientId:string;rows:DailyWeight[];onSaved:()=>Promise<void>}) {
 const [initial,setInitial]=useState<number|null>(null);const [initialError,setInitialError]=useState(false);
 useEffect(()=>{let active=true;setInitial(null);setInitialError(false);loadInitialMeasurements(patientId).then(r=>{if(active)setInitial(r?.initial_weight_kg??null);}).catch(()=>{if(active)setInitialError(true);});return()=>{active=false;};},[patientId]);
 const [date,setDate]=useState(localDate());const [value,setValue]=useState('');const [period,setPeriod]=useState('all');const [smooth,setSmooth]=useState(false);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const sorted=rows.filter(r=>r.patient_id===patientId).slice().sort((a,b)=>a.recorded_on.localeCompare(b.recorded_on)||a.created_at.localeCompare(b.created_at));
 const range=measurementRange(period==='all'?'30':period,'','');const filtered=sorted.filter(r=>period==='all'||r.recorded_on>=range.from&&r.recorded_on<=range.to);
 const last=sorted.at(-1);const first=filtered[0];const latest=filtered.at(-1);const values=filtered.map(r=>r.weight_kg);const min=Math.min(...values);const max=Math.max(...values);
 const save=async()=>{const next=Number(value);setError('');if(!Number.isFinite(next)||next<=0||date>localDate()){setError('Ingresá una fecha no futura y un peso positivo.');return;}if(last&&Math.abs(next-last.weight_kg)/last.weight_kg>=0.1&&!window.confirm(`El peso varía un 10% o más respecto de ${last.weight_kg} kg. ¿Confirmás que es correcto?`))return;setBusy(true);try{await recordWeight(patientId,date,next,requestId);setValue('');setRequestId(crypto.randomUUID());await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="space-y-4"><Card className="space-y-4"><h2 className="text-lg font-bold">Seguimiento de peso</h2><p className="text-sm text-text-secondary">Registro cotidiano opcional, separado de Antropometría.</p><form onSubmit={e=>{e.preventDefault();void save();}} className="grid sm:grid-cols-3 gap-3"><label className="form-label">Fecha<input className="form-control" type="date" required max={localDate()} value={date} onChange={e=>{setDate(e.target.value);setRequestId(crypto.randomUUID());}} /></label><label className="form-label">Peso (kg)<input className="form-control" type="number" required min="0.1" max="1000" step="0.1" value={value} onChange={e=>{setValue(e.target.value);setRequestId(crypto.randomUUID());}} /></label><Button className="self-end" disabled={busy}>{busy?'Guardando…':'Guardar peso'}</Button></form>{error&&<p role="alert" className="text-semantic-critical text-sm">{error}</p>}</Card>
 <Card className="space-y-4"><div className="grid sm:grid-cols-2 gap-3"><div><p className="text-xs text-text-secondary">Último peso registrado {last?`(${displayMeasurementDate(last.recorded_on)})`:''}</p><p className="font-bold text-xl">{last?`${last.weight_kg} kg`:'Sin registros'}</p></div><div><p className="text-xs text-text-secondary">Cambio del período</p><p className="font-bold text-xl">{first&&latest&&first!==latest?`${(latest.weight_kg-first.weight_kg).toFixed(1)} kg`:'—'}</p></div></div>
 <div><p className="text-xs text-text-secondary">Cambio de peso desde inicio</p><p className="font-bold text-xl">{initialError?'No disponible':initial!==null&&last?`${(last.weight_kg-initial).toFixed(1)} kg`:'Sin referencia inicial'}</p>{initial!==null&&<p className="text-xs text-text-secondary">Peso inicial: {initial} kg · independiente del período elegido</p>}</div>
 <div className="flex flex-wrap gap-1">{[['7','7 días'],['30','30 días'],['90','3 meses'],['all','Todo']].map(([v,l])=><Button key={v} variant={period===v?'primary':'ghost'} aria-pressed={period===v} onClick={()=>setPeriod(v!)}>{l}</Button>)}</div>
 {filtered.length?<div className="overflow-x-auto"><div className="relative h-52 flex items-end gap-3 px-2 pb-8 pt-7" style={{minWidth:Math.max(240,filtered.length*65)}}>{filtered.map(r=><div key={r.id} className="flex-1 text-center relative"><span className="block text-xs mb-1">{r.weight_kg}</span><div className="bg-brand-primary rounded-t-lg mx-auto max-w-12" style={{height: min===max?80:30+(r.weight_kg-min)/(max-min)*90}}/><span className="absolute top-full inset-x-0 mt-1 text-[10px] whitespace-nowrap">{displayMeasurementDate(r.recorded_on)}</span></div>)}{smooth&&filtered.length>=3&&<svg aria-label="Media móvil de tres registros" className="absolute inset-x-2 bottom-8 w-[calc(100%-16px)] h-[120px] pointer-events-none" viewBox="0 0 1000 120" preserveAspectRatio="none"><polyline fill="none" stroke="var(--brand-strong)" strokeWidth="2" vectorEffect="non-scaling-stroke" points={filtered.map((_,i)=>{const part=values.slice(Math.max(0,i-1),Math.min(values.length,i+2));const avg=part.reduce((a,b)=>a+b,0)/part.length;return `${(i+.5)/values.length*1000},${120-(min===max?80:30+(avg-min)/(max-min)*90)}`;}).join(' ')} /></svg>}</div></div>:<p>No hay registros en este período.</p>}
 <label className="flex gap-2 items-center text-sm min-h-11"><input type="checkbox" checked={smooth} disabled={filtered.length<3} onChange={e=>setSmooth(e.target.checked)}/>Mostrar línea de tendencia</label><p className="text-xs text-text-secondary">Media móvil de hasta tres registros. Describe datos anteriores, sin juicios ni proyecciones.</p></Card>
 <Card><h3 className="font-bold mb-3">Historial de peso</h3>{filtered.slice().reverse().map(r=><div key={r.id} className="flex justify-between gap-3 border-t border-border-subtle py-3"><div className="text-sm">{displayMeasurementDate(r.recorded_on)}<p className="text-xs text-text-secondary">Registrado por {r.origin==='patient'?'el paciente':'el profesional'}</p></div><strong>{r.weight_kg} kg</strong></div>)}</Card></div>;
}
