import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {Archive,RotateCcw,Search,X} from 'lucide-react';
import {loadClinicalPatients,setPatientStatus,type ClinicalPatient} from '../../data/supabase/patient-profile.repository';
import {Card} from '../ui/Card';
import {Button} from '../ui/Button';
import {Badge} from '../ui/Badge';
import {Dialog} from '../ui/Dialog';

export function RealAnthropometryPatientList({organizationId,refreshKey=0,onCount}:{organizationId?:string;refreshKey?:number;onCount?:(count:number)=>void}){
 const [patients,setPatients]=useState<ClinicalPatient[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState<'active'|'archived'|'all'>('active'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[changing,setChanging]=useState<ClinicalPatient|null>(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');loadClinicalPatients().then(rows=>{if(active){setPatients(rows);onCount?.(rows.filter(p=>p.status==='active'&&(!organizationId||p.organization_id===organizationId)).length);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[retry,refreshKey,organizationId,onCount]);
 const rows=useMemo(()=>patients.filter(p=>(!organizationId||p.organization_id===organizationId)&&(status==='all'||p.status===status)&&[p.first_name,p.last_name,p.email].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())),[patients,organizationId,status,query]);
 const activeCount=patients.filter(p=>p.status==='active'&&(!organizationId||p.organization_id===organizationId)).length;
 const archivedCount=patients.filter(p=>p.status==='archived'&&(!organizationId||p.organization_id===organizationId)).length;
 const changeStatus=async()=>{if(!changing)return;setBusy(true);setActionError('');try{await setPatientStatus(changing.id,changing.status==='active'?'archived':'active');setChanging(null);setRetry(n=>n+1);}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}};
 return <Card className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Mis pacientes</h2><p className="mt-1 text-xs text-text-secondary">{activeCount} activos{archivedCount?` · ${archivedCount} archivados`:''}</p></div><div className="flex gap-1" role="group" aria-label="Filtrar por estado">{([['active','Activos'],['archived','Archivados'],['all','Todos']] as const).map(([value,label])=><Button key={value} size="sm" variant={status===value?'secondary':'ghost'} aria-pressed={status===value} onClick={()=>setStatus(value)}>{label}</Button>)}</div></div><label className="relative block"><span className="sr-only">Buscar por nombre o correo</span><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-text-tertiary"/><input className="form-control pl-10 pr-10" placeholder="Buscar por nombre o correo…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label="Limpiar búsqueda" onClick={()=>setQuery('')} className="absolute right-2 top-1.5 flex h-8 w-8 items-center justify-center"><X className="h-4 w-4"/></button>}</label>{loading?<p role="status">Cargando pacientes…</p>:error?<div><p role="alert">{error}</p><Button onClick={()=>setRetry(n=>n+1)}>Reintentar</Button></div>:rows.length?<div className="divide-y divide-border-subtle">{rows.map(p=><div key={p.id} className="flex flex-col gap-3 py-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Link className="font-semibold text-text-primary hover:text-brand-strong" to={`/professional/patients/${p.id}`}>{p.first_name} {p.last_name}</Link><Badge variant={p.status==='active'?'active':'neutral'}>{p.status==='active'?'Activo':'Archivado'}</Badge></div><p className="truncate text-sm text-text-secondary">{p.email??'Sin correo'}{p.phone?` · ${p.phone}`:''}</p></div><div className="flex gap-2"><Link className="inline-flex min-h-11 items-center px-3 text-sm font-semibold text-brand-strong" to={`/professional/patients/${p.id}`}>Abrir ficha</Link><Button size="sm" variant="ghost" onClick={()=>{setChanging(p);setActionError('');}}>{p.status==='active'?<Archive className="h-4 w-4"/>:<RotateCcw className="h-4 w-4"/>}{p.status==='active'?'Archivar':'Reactivar'}</Button></div></div>)}</div>:<div className="rounded-xl bg-surface-subtle p-5 text-center"><p className="font-semibold">{query?'No encontramos pacientes con esa búsqueda.':status==='archived'?'No tenés pacientes archivados.':'Todavía no hay pacientes activos.'}</p><p className="mt-1 text-sm text-text-secondary">{query?'Probá con otro nombre o correo.':status==='active'?'Invitá a tu primer paciente para comenzar.':'Cuando archives una ficha aparecerá aquí.'}</p></div>}
 {changing&&<Dialog isOpen onClose={()=>!busy&&setChanging(null)} title={changing.status==='active'?'Archivar paciente':'Reactivar paciente'} description={changing.status==='active'?'La ficha y todo su historial se conservan. El paciente dejará de operar hasta que lo reactives.':'La ficha volverá a estar disponible para el trabajo clínico.'}><div className="space-y-4"><p className="text-sm">{changing.first_name} {changing.last_name}</p>{actionError&&<p role="alert" className="rounded-xl bg-critical/10 p-3 text-sm text-critical">{actionError}</p>}<div className="flex justify-end gap-2"><Button variant="secondary" disabled={busy} onClick={()=>setChanging(null)}>Cancelar</Button><Button variant={changing.status==='active'?'destructive':'primary'} disabled={busy} onClick={()=>void changeStatus()}>{busy?'Guardando…':changing.status==='active'?'Archivar ficha':'Reactivar ficha'}</Button></div></div></Dialog>}
 </Card>;
}
