import {useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {loadClinicalPatients,loadRecentPatientAppointments,type ClinicalPatient,type RecentPatientAppointment} from '../../../data/supabase/patient-profile.repository';
import {loadProfessionalMealPlans} from '../../../data/supabase/clinical-meal-plans.repository';
import type {RealProfessionalMealPlan} from '../../../data/clinical-meal-plans.types';
import {RealInitialMeasurements} from '../../../components/domain/RealInitialMeasurements';
import {RealDailyFollowupPage} from '../shared/RealDailyFollowupPage';
import {RealPatientAnthropometryPage} from './RealPatientAnthropometryPage';
import {Card} from '../../../components/ui/Card';
import {Button} from '../../../components/ui/Button';
const tabs=[['basic','Información básica'],['plans','Plan alimentario'],['checkins','Historial de check-ins'],['weight','Seguimiento de peso'],['anthropometry','Antropometría']] as const;
export function RealPatientDetailPage(){
 const {patientId=''}=useParams();const [params,setParams]=useSearchParams();const requestedTab=params.get('tab');const tab=tabs.some(([key])=>key===requestedTab)?requestedTab!:'basic';
 const [person,setPerson]=useState<ClinicalPatient|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setPerson(null);setError('');loadClinicalPatients().then(rows=>{if(active){const p=rows.find(p=>p.id===patientId);if(!p)throw new Error('Ficha no disponible o sin acceso vigente.');setPerson(p);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[patientId,retry]);
 const selectedTab=person?.status==='archived'?'basic':tab;
 const availableTabs=tabs.filter(([key])=>person?.status==='active'||key==='basic');
 return <div className="max-w-6xl mx-auto p-4 sm:p-6 space-y-5"><Link className="inline-flex min-h-11 items-center text-sm text-brand-strong" to="/professional/patients">← Volver a pacientes</Link>{loading?<p role="status">Cargando ficha…</p>:error?<Card><p role="alert">{error}</p><Button onClick={()=>setRetry(n=>n+1)}>Reintentar</Button></Card>:person&&<><Card highlighted><h1 className="font-bold text-2xl">{person.first_name} {person.last_name}</h1><p className="text-sm text-text-secondary break-words">{person.email??'Sin correo'} · {person.phone??'Sin teléfono'}</p>{person.status==='archived'&&<p className="mt-2 text-sm font-semibold text-text-secondary">Ficha archivada · historial conservado y operación clínica suspendida.</p>}</Card><div className="sm:hidden"><label className="form-label" htmlFor="patient-section">Sección de la ficha</label><select id="patient-section" className="form-control" value={selectedTab} onChange={event=>setParams({tab:event.target.value})}>{availableTabs.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><nav aria-label="Secciones de la ficha" className="hidden flex-wrap gap-1 sm:flex">{availableTabs.map(([key,label])=><Button key={key} variant={selectedTab===key?'primary':'ghost'} aria-pressed={selectedTab===key} onClick={()=>setParams({tab:key})}>{label}</Button>)}</nav>
 {selectedTab==='basic'&&<><Card><h2 className="font-bold mb-3">Información básica</h2><dl className="grid sm:grid-cols-2 gap-4 text-sm">{[['Correo',person.email],['Teléfono',person.phone],['Ciudad',person.city],['Fecha de nacimiento',person.birth_date],['Estado',person.status==='active'?'Activo':'Archivado']].map(([k,v])=><div key={k}><dt className="text-text-secondary">{k}</dt><dd className="break-words">{v||'Sin informar'}</dd></div>)}</dl></Card>{person.status==='active'&&<><RecentAppointments patientId={patientId}/><RealInitialMeasurements key={patientId} patientId={patientId}/></>}</>}
 {selectedTab==='plans'&&<PatientPlans patientId={patientId}/>}
 {selectedTab==='anthropometry'&&<RealPatientAnthropometryPage embedded/>}
 {(selectedTab==='checkins'||selectedTab==='weight')&&<RealDailyFollowupPage key={`${patientId}-${selectedTab}`} section={selectedTab} embedded/>}
 </>}</div>;
}
function PatientPlans({patientId}:{patientId:string}){const [rows,setRows]=useState<RealProfessionalMealPlan[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;loadProfessionalMealPlans().then(r=>{if(active)setRows(r.filter(p=>p.patientId===patientId));}).catch(()=>{if(active)setError('No pudimos cargar los planes. Volvé a abrir esta sección para reintentar.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[patientId]);return <div className="space-y-3">{loading?<p role="status">Cargando planes…</p>:error?<p role="alert">{error}</p>:rows.length?rows.map(p=><Card key={p.id}><h2 className="font-bold">{p.title}</h2><p className="text-sm text-text-secondary">{p.status==='published'?'Publicado':p.status==='draft'?'Borrador':'Archivado'} · {p.pendingCommentCount} comentarios por revisar</p><Link className="inline-flex min-h-11 items-center text-brand-strong" to={`/professional/meal-plans/${p.id}`}>Abrir plan y cumplimiento →</Link></Card>):<Card>No hay planes vinculados a este paciente.</Card>}<Link className="inline-flex min-h-11 items-center text-brand-strong" to="/professional/meal-plans">Ir a la biblioteca de planes</Link></div>;}

function RecentAppointments({patientId}:{patientId:string}){const [rows,setRows]=useState<RecentPatientAppointment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;loadRecentPatientAppointments(patientId).then(data=>active&&setRows(data)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[patientId]);const status:Record<string,string>={requested:'Solicitada',confirmed:'Confirmada',completed:'Completada',cancelled_by_patient:'Cancelada por paciente',cancelled_by_professional:'Cancelada por profesional',rescheduled:'Reprogramada',no_show:'Ausente'};const payment:Record<string,string>={paid:'Pagada',partial:'Pago parcial',pending:'Pendiente',refunded:'Reembolsada',no_charge:'Sin cargo'};return <Card><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="font-bold">Últimos turnos</h2><p className="mt-1 text-xs text-text-secondary">Vista informativa; los cambios se realizan desde Agenda o Citas.</p></div><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-brand-strong" to="/professional/appointments">Ver historial</Link></div>{loading?<p className="mt-4" role="status">Cargando turnos…</p>:error?<p className="mt-4" role="alert">{error}</p>:rows.length?<div className="mt-3 divide-y divide-border-subtle">{rows.map(row=><div key={row.id} className="grid gap-1 py-3 text-sm sm:grid-cols-[1.4fr_1fr_1fr]"><span className="font-semibold">{new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(row.starts_at))}</span><span>{row.modality==='virtual'?'Virtual':'Presencial'} · {status[row.status]??row.status}</span><span className="text-text-secondary sm:text-right">{payment[row.payment_status]??row.payment_status}</span></div>)}</div>:<p className="mt-4 rounded-xl bg-surface-subtle p-4 text-sm text-text-secondary">Todavía no hay turnos registrados.</p>}</Card>;}
