/* eslint-disable jsx-a11y/no-autofocus */
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Copy, Pencil, Plus, Search, Sparkles, Trash2, Users, X } from 'lucide-react';
import { useAuth } from '../../../auth/AuthProvider';
import { assignPhrase, loadDaily, savePhrase, type DailyData, type DailyPhrase } from '../../../data/supabase/daily-followup.repository';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Dialog } from '../../../components/ui/Dialog';
import { useToast } from '../../../components/ui/Toast';
import { MobileFilters } from '../../../components/ui/MobileFilters';
import { MobileActions } from '../../../components/ui/MobileActions';

const empty: DailyData={patients:[],weights:[],checkins:[],lists:[],tasks:[],phrases:[],assignments:[]};

export function RealRecommendationsPage() {
 const {accessContext}=useAuth(); const {showToast}=useToast();
 const organizations=useMemo(()=>accessContext?.memberships.filter(m=>m.role==='nutritionist'&&m.membership_status==='active'&&m.organization_status==='active')??[],[accessContext]);
 const [data,setData]=useState<DailyData>(empty);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [org,setOrg]=useState('');const [search,setSearch]=useState('');const [assignmentFilter,setAssignmentFilter]=useState('');
 const [editor,setEditor]=useState<DailyPhrase|'new'|null>(null);const [assigning,setAssigning]=useState<DailyPhrase|null>(null);const [removing,setRemoving]=useState<DailyPhrase|null>(null);const [picked,setPicked]=useState<string[]>([]);const [patientSearch,setPatientSearch]=useState('');
 useEffect(()=>{if(!org&&organizations[0])setOrg(organizations[0].organization_id);},[org,organizations]);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{setData(await loadDaily());}catch(cause){setError(cause instanceof Error?cause.message:'No pudimos cargar las recomendaciones.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 const phrases=data.phrases.filter(p=>(!org||p.organization_id===org)&&p.text.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).filter(p=>{const count=data.assignments.filter(a=>a.phrase_id===p.id).length;return assignmentFilter==='assigned'?count>0:assignmentFilter==='empty'?count===0:true;});
 const patients=data.patients.filter(p=>p.organization_id===assigning?.organization_id&&`${p.first_name} ${p.last_name}`.toLocaleLowerCase().includes(patientSearch.toLocaleLowerCase()));
 const run=async(action:()=>Promise<unknown>,title:string)=>{setBusy(true);setError('');try{await action();await refresh();showToast(title,'Los cambios ya quedaron guardados.');return true;}catch(cause){setError(cause instanceof Error?cause.message:'No pudimos guardar los cambios.');return false;}finally{setBusy(false);}};
 const openAssignment=(phrase:DailyPhrase)=>{setAssigning(phrase);setPicked(data.assignments.filter(a=>a.phrase_id===phrase.id).map(a=>a.patient_id));setPatientSearch('');};
 if(!organizations.length)return <main className="mx-auto max-w-3xl p-4 sm:p-8"><Card className="py-10 text-center"><Sparkles className="mx-auto h-9 w-9 text-text-tertiary"/><h1 className="mt-3 text-lg font-bold">Recomendaciones no disponibles</h1><p className="mt-2 text-sm text-text-secondary">Necesitás un rol de nutricionista activo.</p></Card></main>;
 return <main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6 lg:p-8">
  <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-soft text-brand-strong"><Sparkles className="h-6 w-6"/></span><div><h1 className="text-2xl font-bold">Recomendaciones</h1><p className="mt-1 text-sm text-text-secondary">Creá mensajes breves y elegí cuál verá cada paciente.</p></div></div><Button onClick={()=>setEditor('new')} disabled={!org}><Plus className="h-4 w-4"/>Nueva frase</Button></header>
  <section className="grid gap-3 sm:grid-cols-3" aria-label="Resumen"><Card className="!p-4"><p className="text-xl font-bold">{data.phrases.filter(p=>!org||p.organization_id===org).length}</p><p className="text-xs text-text-secondary">Frases propias</p></Card><Card className="!p-4"><p className="text-xl font-bold">{new Set(data.assignments.filter(a=>data.phrases.some(p=>p.id===a.phrase_id&&(!org||p.organization_id===org))).map(a=>a.patient_id)).size}</p><p className="text-xs text-text-secondary">Pacientes con frase activa</p></Card><Card className="!p-4"><p className="text-xl font-bold">{data.phrases.filter(p=>(!org||p.organization_id===org)&&!data.assignments.some(a=>a.phrase_id===p.id)).length}</p><p className="text-xs text-text-secondary">Sin asignar</p></Card></section>
  <Card className="space-y-3"><MobileFilters activeCount={[search,assignmentFilter].filter(Boolean).length} className="gap-3 lg:grid-cols-[minmax(220px,1fr)_220px_220px_auto]"><label className="relative"><span className="sr-only">Buscar frases</span><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-text-tertiary"/><input className="form-control pl-10 pr-12" placeholder="Buscar por texto…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button type="button" aria-label="Limpiar búsqueda" onClick={()=>setSearch('')} className="absolute right-0 top-0 flex h-11 w-11 items-center justify-center"><X className="h-4 w-4"/></button>}</label>{organizations.length>1&&<select aria-label="Consultorio" className="form-control" value={org} onChange={e=>setOrg(e.target.value)}>{organizations.map(m=><option key={m.organization_id} value={m.organization_id}>{m.organization_name}</option>)}</select>}<select aria-label="Asignación" className="form-control" value={assignmentFilter} onChange={e=>setAssignmentFilter(e.target.value)}><option value="">Todas</option><option value="assigned">Con pacientes</option><option value="empty">Sin asignar</option></select><Button variant="ghost" disabled={!search&&!assignmentFilter} onClick={()=>{setSearch('');setAssignmentFilter('');}}>Limpiar</Button></MobileFilters><p className="text-xs text-text-secondary">{phrases.length} recomendaciones</p></Card>
  {error&&<Card><p role="alert" className="text-sm text-critical">{error}</p></Card>}{loading?<Card><p role="status">Cargando recomendaciones…</p></Card>:!phrases.length?<Card className="py-12 text-center"><Sparkles className="mx-auto h-8 w-8 text-text-tertiary"/><h2 className="mt-3 font-bold">{search||assignmentFilter?'No encontramos frases':'Todavía no creaste recomendaciones'}</h2><p className="mt-1 text-sm text-text-secondary">Creá mensajes reutilizables y asignálos cuando los necesites.</p></Card>:<section className="overflow-hidden rounded-2xl border border-border-subtle bg-surface" aria-label="Listado de recomendaciones">{phrases.map(phrase=>{const assigned=data.assignments.filter(a=>a.phrase_id===phrase.id);const names=assigned.map(a=>data.patients.find(p=>p.id===a.patient_id)).filter(Boolean).map(p=>`${p!.first_name} ${p!.last_name}`);return <article key={phrase.id} className="grid gap-3 border-b border-border-subtle p-4 last:border-0 hover:bg-surface-subtle/60 lg:grid-cols-[minmax(0,1fr)_minmax(180px,300px)_auto] lg:items-center"><blockquote className="min-w-0 whitespace-pre-wrap text-sm font-semibold leading-relaxed">“{phrase.text}”</blockquote><div className="min-w-0"><Badge variant={assigned.length?'active':'neutral'}>{assigned.length?`${assigned.length} ${assigned.length===1?'paciente':'pacientes'}`:'Sin asignar'}</Badge><p className="mt-1 truncate text-xs text-text-secondary" title={names.join(', ')}>{names.join(', ')||'Ningún paciente verá esta frase todavía.'}</p></div><MobileActions title="Acciones de recomendación"><Button variant="ghost" onClick={()=>setEditor(phrase)}><Pencil className="h-4 w-4"/>Editar</Button><Button variant="ghost" disabled={busy} onClick={()=>void run(()=>savePhrase(phrase.organization_id,phrase.text),'Frase duplicada')}><Copy className="h-4 w-4"/>Duplicar</Button><Button variant="secondary" onClick={()=>openAssignment(phrase)}><Users className="h-4 w-4"/>Aplicar</Button><Button variant="ghost" onClick={()=>setRemoving(phrase)}><Trash2 className="h-4 w-4"/>Eliminar</Button></MobileActions><div className="hidden flex-wrap justify-end gap-1 border-t border-border-subtle pt-2 sm:flex lg:border-0 lg:pt-0"><Button size="sm" variant="ghost" aria-label="Editar frase" onClick={()=>setEditor(phrase)}><Pencil className="h-4 w-4"/>Editar</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run(()=>savePhrase(phrase.organization_id,phrase.text),'Frase duplicada')}><Copy className="h-4 w-4"/>Duplicar</Button><Button size="sm" variant="secondary" onClick={()=>openAssignment(phrase)}><Users className="h-4 w-4"/>Aplicar</Button><Button size="sm" variant="ghost" aria-label="Eliminar frase" onClick={()=>setRemoving(phrase)}><Trash2 className="h-4 w-4"/></Button></div></article>;})}</section>}
  {editor&&<PhraseDialog value={editor} organizationId={org} busy={busy} onClose={()=>setEditor(null)} onSave={async(text)=>{const previous=editor==='new'?undefined:editor;if(await run(()=>savePhrase(previous?.organization_id??org,text,previous),previous?'Recomendación actualizada':'Recomendación creada'))setEditor(null);}}/>}
  <Dialog isOpen={Boolean(assigning)} onClose={()=>setAssigning(null)} title="Aplicar recomendación" description="Cada paciente puede tener una sola frase activa; esta selección reemplaza la anterior."><div className="space-y-3"><input className="form-control" aria-label="Buscar pacientes" placeholder="Buscar paciente…" value={patientSearch} onChange={e=>setPatientSearch(e.target.value)}/><p className="text-xs text-text-secondary">{picked.length} seleccionados</p><div className="max-h-72 space-y-1 overflow-auto">{patients.map(p=><label key={p.id} className="flex min-h-11 items-center gap-3 rounded-xl px-3 hover:bg-surface-subtle"><input type="checkbox" checked={picked.includes(p.id)} onChange={e=>setPicked(old=>e.target.checked?[...new Set([...old,p.id])]:old.filter(id=>id!==p.id))}/><span>{p.first_name} {p.last_name}</span></label>)}{!patients.length&&<p className="p-3 text-sm text-text-secondary">No encontramos pacientes.</p>}</div>{error&&<p role="alert" className="text-sm text-critical">{error}</p>}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setAssigning(null)}>Cancelar</Button><Button disabled={busy} onClick={async()=>{if(assigning&&await run(()=>assignPhrase(assigning.id,picked),'Asignación actualizada'))setAssigning(null);}}>Guardar asignación</Button></div></div></Dialog>
  <Dialog isOpen={Boolean(removing)} onClose={()=>setRemoving(null)} title="Eliminar recomendación" description={removing&&data.assignments.some(a=>a.phrase_id===removing.id)?'También dejará de mostrarse a los pacientes que la tienen activa. Esta acción conserva la auditoría.':'La frase dejará de estar disponible. Esta acción conserva la auditoría.'}><div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setRemoving(null)}>Cancelar</Button><Button variant="destructive" disabled={busy} onClick={async()=>{if(removing&&await run(()=>savePhrase(removing.organization_id,removing.text,removing,true),'Recomendación eliminada'))setRemoving(null);}}>Eliminar</Button></div></Dialog>
 </main>;
}

function PhraseDialog({value,organizationId,busy,onClose,onSave}:{value:DailyPhrase|'new';organizationId:string;busy:boolean;onClose:()=>void;onSave:(text:string)=>Promise<void>}){const [text,setText]=useState(value==='new'?'':value.text);return <Dialog isOpen onClose={onClose} title={value==='new'?'Nueva recomendación':'Editar recomendación'} description={value==='new'?'Escribí un mensaje breve, positivo y reutilizable.':'Si está aplicada, el cambio será visible inmediatamente para esos pacientes.'}><form className="space-y-4" onSubmit={e=>{e.preventDefault();void onSave(text.trim());}}><label className="form-label">Mensaje *<textarea autoFocus required maxLength={280} rows={4} className="form-control" value={text} onChange={e=>setText(e.target.value)}/><span className="mt-1 block text-right text-xs font-normal text-text-secondary">{text.length}/280</span></label><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button disabled={busy||!organizationId||!text.trim()}>{busy?'Guardando…':'Guardar recomendación'}</Button></div></form></Dialog>}
