import { ArrowDown, ArrowLeft, ArrowUp, Check, ChevronDown, Copy, GripVertical, MessageSquareText, Minus, Plus, Save, Send, Trash2, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Dialog } from '../../../components/ui/Dialog';
import { useToast } from '../../../components/ui/Toast';
import { assignMealPlan, loadMealPlanActivity, loadProfessionalMealPlans, loadProfessionalPatients, publishMealPlan, retireMealPlan, reviewMealPlanComment, updateMealPlanDraft } from '../../../data/supabase/clinical-meal-plans.repository';
import type { ClinicalMealPlanContent, ClinicalMealPlanDay, ClinicalMealPlanMeal, RealMealPlanActivity, RealProfessionalMealPlan, RealProfessionalPatient } from '../../../data/clinical-meal-plans.types';

const mealNames = ['Desayuno', 'Almuerzo', 'Merienda', 'Cena'] as const;
const inputClass = 'form-control min-h-11';
const cloneContent = (content: ClinicalMealPlanContent) => structuredClone(content);
const cloneDay = (day: ClinicalMealPlanDay): ClinicalMealPlanDay => ({ ...structuredClone(day), id: crypto.randomUUID(), meals: day.meals.map(meal => ({ ...structuredClone(meal), id: crypto.randomUUID(), items: meal.items.map(item => ({ ...structuredClone(item), id: crypto.randomUUID() })) })) });
const statusLabel = (status?: RealMealPlanActivity['adherenceStatus']) => status === 'completed' ? 'Cumplida' : status === 'partial' ? 'Parcial' : status === 'not_completed' ? 'No cumplida' : 'Sin marcar';
const statusVariant = (status?: RealMealPlanActivity['adherenceStatus']): 'active' | 'pending' | 'high' | 'neutral' => status === 'completed' ? 'active' : status === 'partial' ? 'pending' : status === 'not_completed' ? 'high' : 'neutral';

export function RealMealPlanEditorPage() {
  const { planId } = useParams(); const { showToast } = useToast(); const navigate = useNavigate();
  const [plan, setPlan] = useState<RealProfessionalMealPlan | null>(null); const [content, setContent] = useState<ClinicalMealPlanContent | null>(null); const [title, setTitle] = useState('');
  const [recipes, setRecipes] = useState<LibraryContent[]>([]);
  const [activities, setActivities] = useState<RealMealPlanActivity[]>([]); const [patients, setPatients] = useState<RealProfessionalPatient[]>([]); const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [assignOpen, setAssignOpen] = useState(false); const [patientId, setPatientId] = useState(''); const [kind, setKind] = useState<'primary' | 'complement'>('primary');
  const [expandedDays, setExpandedDays] = useState<Set<string>>(new Set()); const [draggedDayId, setDraggedDayId] = useState<string | null>(null);

  const refresh = async () => {
    if (!planId) return; setLoading(true); setError(null);
    try {
      const [plans, activity, people, library] = await Promise.all([loadProfessionalMealPlans(), loadMealPlanActivity(planId), loadProfessionalPatients(), loadLibrary()]);
      const found = plans.find(item => item.id === planId) ?? null; if (!found) throw new Error();
      setRecipes(library.filter(r => r.kind==='recipe' && r.status==='published' && r.organization_id===found.organizationId));
      setPlan(found); setTitle(found.title); setContent(cloneContent(found.content)); setActivities(activity); setPatients(people); setPatientId(found.patientId ?? people[0]?.id ?? '');
      setExpandedDays(previous => previous.size ? previous : new Set(found.content.days.map(day => day.id)));
    } catch { setError('No pudimos abrir este plan o ya no tenés acceso.'); } finally { setLoading(false); }
  };
  useEffect(() => { void refresh(); }, [planId]);

  const pending = useMemo(() => activities.filter(item => item.patientComment && !item.reviewedAt), [activities]);
  const activityByMeal = useMemo(() => new Map(activities.map(item => [`${item.dayId}:${item.mealId}`, item])), [activities]);
  const markedCount = activities.filter(item => item.adherenceStatus).length; const completedCount = activities.filter(item => item.adherenceStatus === 'completed').length;
  const updateDay = (dayId: string, update: (day: ClinicalMealPlanDay) => ClinicalMealPlanDay) => setContent(previous => previous ? { ...previous, days: previous.days.map(day => day.id === dayId ? update(day) : day) } : previous);
  const updateMeal = (dayId: string, mealId: string, update: (meal: ClinicalMealPlanMeal) => ClinicalMealPlanMeal) => updateDay(dayId, day => ({ ...day, meals: day.meals.map(meal => meal.id === mealId ? update(meal) : meal) }));
  const toggleDay = (dayId: string) => setExpandedDays(previous => { const next = new Set(previous); if (next.has(dayId)) next.delete(dayId); else next.add(dayId); return next; });
  const addMeal = (dayId: string) => updateDay(dayId, day => { if (day.meals.length >= 4) return day; const type = mealNames.find(name => !day.meals.some(meal => meal.type === name)) ?? `Comida ${day.meals.length + 1}`; return { ...day, meals: [...day.meals, { id: crypto.randomUUID(), type, items: [{ id: crypto.randomUUID(), description: '', quantity: '' }] }] }; });
  const addDay = () => { if (!content || content.days.length >= 30) return; const id = crypto.randomUUID(); setContent({ ...content, days: [...content.days, { id, meals: [] }] }); setExpandedDays(previous => new Set(previous).add(id)); };
  const duplicateDay = (index: number) => { if (!content || content.days.length >= 30) return; const copy = cloneDay(content.days[index]!); setContent({ ...content, days: [...content.days.slice(0, index + 1), copy, ...content.days.slice(index + 1)] }); setExpandedDays(previous => new Set(previous).add(copy.id)); };
  const removeDay = (index: number) => { if (!content || content.days.length <= 7) { showToast('Mínimo de días', 'Los planes deben conservar al menos 7 días.', 'error'); return; } const removed = content.days[index]!; setContent({ ...content, days: content.days.filter((_, current) => current !== index) }); setExpandedDays(previous => { const next = new Set(previous); next.delete(removed.id); return next; }); };
  const moveDay = (from: number, to: number) => { if (!content || from === to || from < 0 || to < 0 || to >= content.days.length) return; const days = [...content.days]; const [moved] = days.splice(from, 1); if (!moved) return; days.splice(to, 0, moved); setContent({ ...content, days }); };

  const save = async () => { if (!plan || !content) return false; setSaving(true); try { await updateMealPlanDraft(plan.id, title, content); showToast('Borrador guardado', 'Los cambios todavía no son visibles para el paciente.'); await refresh(); return true; } catch { showToast('No pudimos guardar', 'Revisá que cada elemento tenga una descripción.', 'error'); return false; } finally { setSaving(false); } };
  const assign = async () => { if (!plan || !patientId) return; try { await assignMealPlan(plan.id, patientId, kind); setAssignOpen(false); showToast('Plan preparado', 'Ahora publicá los cambios para que el paciente lo vea.'); await refresh(); } catch { showToast('No pudimos asignar', 'El paciente debe estar asignado a tu cuenta y el plan no puede pertenecer a otra persona.', 'error'); } };
  const publish = async () => { if (!plan || !await save()) return; setSaving(true); try { await publishMealPlan(plan.id); showToast('Cambios publicados', 'El paciente ya ve la versión nueva de su plan.'); await refresh(); } catch { showToast('No pudimos publicar', 'El plan necesita entre 7 y 30 días y cada comida debe tener al menos un elemento.', 'error'); } finally { setSaving(false); } };
  const retire = async () => { if (!plan || !window.confirm('¿Retirar este plan? El paciente dejará de verlo.')) return; try { await retireMealPlan(plan.id); showToast('Plan retirado', 'El plan dejó de estar visible para el paciente.'); navigate('/professional/meal-plans'); } catch { showToast('No pudimos retirar el plan', 'Intentá nuevamente.', 'error'); } };

  if (loading) return <div className="mx-auto max-w-6xl p-6"><p role="status" className="text-sm text-text-secondary">Cargando plan…</p></div>;
  if (error || !plan || !content) return <div className="mx-auto max-w-6xl p-6"><Card><p className="text-sm text-semantic-critical">{error}</p><Button asChild className="mt-4" variant="secondary"><Link to="/professional/meal-plans">Volver a planes</Link></Button></Card></div>;
  const totalMeals = content.days.reduce((sum, day) => sum + day.meals.length, 0);

  return <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 flex-1"><Link to="/professional/meal-plans" className="inline-flex min-h-11 items-center gap-1 text-xs font-semibold text-text-secondary"><ArrowLeft className="h-4 w-4" />Biblioteca de planes</Link><label className="mt-2 block text-xs font-semibold text-text-secondary" htmlFor="editor-title">Título general del plan</label><input id="editor-title" className="mt-1 w-full max-w-xl border-0 border-b border-border-subtle bg-transparent p-0 pb-1 text-2xl font-bold outline-none focus:border-brand-strong focus:ring-0" value={title} onChange={event => setTitle(event.target.value)} maxLength={120} /></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => void save()} disabled={saving}><Save className="h-4 w-4" />Guardar borrador</Button>{!plan.patientId ? <Button onClick={() => setAssignOpen(true)}><UserRound className="h-4 w-4" />Asignar</Button> : <Button onClick={() => void publish()} disabled={saving}><Send className="h-4 w-4" />Publicar cambios</Button>}</div></div>

    <Card highlighted><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold">{plan.patientName ? `Paciente: ${plan.patientName}` : 'Todavía sin paciente asignado'}</p><p className="mt-1 text-xs text-text-secondary">{plan.assignmentStatus === 'active' ? 'La versión publicada está visible para el paciente.' : plan.patientId ? 'Asignado pendiente de publicación.' : 'Al asignarlo quedará ligado exclusivamente a esa persona.'}</p>{plan.patientId && <div className="mt-3 flex flex-wrap gap-2"><Badge variant="active">{completedCount} cumplidas</Badge><Badge variant="neutral">{markedCount} de {totalMeals} marcadas</Badge>{pending.length > 0 && <Badge variant="pending">{pending.length} comentarios nuevos</Badge>}</div>}</div>{plan.patientId && <Button variant="destructive" size="sm" onClick={() => void retire()}>Retirar plan</Button>}</div></Card>

    {pending.length > 0 && <Card className="border-semantic-warning"><div className="flex items-center gap-2"><MessageSquareText className="h-5 w-5 text-semantic-warning" /><h2 className="font-bold">Comentarios nuevos</h2></div><div className="mt-3 space-y-2">{pending.map(item => <div key={item.id} className="flex flex-col gap-2 rounded-xl bg-surface-subtle p-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm">{item.patientComment}</p><Button size="sm" variant="secondary" onClick={() => void reviewMealPlanComment(item.id).then(refresh)}>Marcar revisado</Button></div>)}</div></Card>}

    <section className="space-y-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold">Organización del plan</h2><p className="text-xs text-text-secondary">Plegá, duplicá y reordená los días. Cada uno admite hasta cuatro comidas.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={() => setExpandedDays(new Set())}><Minus className="h-4 w-4" />Plegar todos</Button><Button size="sm" variant="ghost" onClick={() => setExpandedDays(new Set(content.days.map(day => day.id)))}><ChevronDown className="h-4 w-4" />Desplegar todos</Button><Button size="sm" variant="secondary" disabled={content.days.length >= 30} onClick={addDay}><Plus className="h-4 w-4" />Agregar día</Button></div></div>

      {content.days.map((day, index) => {
        const open = expandedDays.has(day.id); const dayActivities = day.meals.map(meal => activityByMeal.get(`${day.id}:${meal.id}`)).filter(Boolean) as RealMealPlanActivity[]; const dayMarked = dayActivities.filter(item => item.adherenceStatus).length;
        return <div key={day.id} draggable onDragStart={() => setDraggedDayId(day.id)} onDragOver={event => event.preventDefault()} onDrop={() => { moveDay(content.days.findIndex(item => item.id === draggedDayId), index); setDraggedDayId(null); }}><Card className="overflow-hidden !p-0">
          <div className="flex items-center gap-2 p-3 sm:px-4"><GripVertical className="h-4 w-4 shrink-0 cursor-grab text-text-tertiary" /><button type="button" className="min-w-0 flex-1 text-left" onClick={() => toggleDay(day.id)} aria-expanded={open}><span className="flex flex-wrap items-center gap-2"><strong className="text-sm">Día {index + 1}</strong>{plan.patientId && day.meals.length > 0 && <Badge variant={dayMarked === day.meals.length ? 'active' : dayMarked ? 'pending' : 'neutral'}>{dayMarked}/{day.meals.length} marcadas</Badge>}</span><span className="mt-0.5 block truncate text-xs text-text-secondary">{day.title?.trim() || 'Sin título adicional'}</span></button><div className="flex shrink-0 items-center gap-0.5"><Button size="sm" variant="ghost" aria-label={`Subir día ${index + 1}`} title="Subir" disabled={!index} onClick={() => moveDay(index, index - 1)}><ArrowUp className="h-4 w-4" /></Button><Button size="sm" variant="ghost" aria-label={`Bajar día ${index + 1}`} title="Bajar" disabled={index === content.days.length - 1} onClick={() => moveDay(index, index + 1)}><ArrowDown className="h-4 w-4" /></Button><Button size="sm" variant="ghost" aria-label={`Duplicar día ${index + 1}`} title="Duplicar" disabled={content.days.length >= 30} onClick={() => duplicateDay(index)}><Copy className="h-4 w-4" /></Button><Button size="sm" variant="ghost" aria-label={`Quitar día ${index + 1}`} title="Quitar" disabled={content.days.length <= 7} onClick={() => removeDay(index)}><Trash2 className="h-4 w-4" /></Button><Button size="sm" variant="ghost" aria-label={`${open ? 'Plegar' : 'Desplegar'} día ${index + 1}`} onClick={() => toggleDay(day.id)}><ChevronDown className={`h-4 w-4 transition-transform ${open ? 'rotate-180' : ''}`} /></Button></div></div>

          {open && <div className="space-y-4 border-t border-border-subtle p-3 sm:p-4"><div><label className="mb-1 block text-[11px] font-semibold text-text-secondary" htmlFor={`title-${day.id}`}>Título adicional opcional</label><input id={`title-${day.id}`} className={inputClass} placeholder="Ej. Día de permitido" value={day.title ?? ''} onChange={event => updateDay(day.id, current => ({ ...current, title: event.target.value }))} /></div><div className="space-y-3">{day.meals.map((meal, mealIndex) => <MealEditor recipes={recipes} key={meal.id} day={day} meal={meal} index={mealIndex} activity={activityByMeal.get(`${day.id}:${meal.id}`)} patientName={plan.patientName} updateMeal={updateMeal} updateDay={updateDay} />)}</div><Button size="sm" variant="secondary" disabled={day.meals.length >= 4} onClick={() => addMeal(day.id)}><Plus className="h-4 w-4" />Agregar comida</Button></div>}
        </Card></div>;
      })}
    </section>

    <Card className="space-y-4"><h2 className="text-base font-bold">Información general del plan</h2><div className="grid gap-4 lg:grid-cols-3"><TextArea label="Objetivos opcionales" id="objectives" value={content.objectives ?? ''} onChange={value => setContent({ ...content, objectives: value })} /><TextArea label="Indicaciones generales" id="indications" value={content.generalIndications ?? ''} onChange={value => setContent({ ...content, generalIndications: value })} /><TextArea label="Lista de compras" id="shopping" value={content.shoppingList ?? ''} onChange={value => setContent({ ...content, shoppingList: value })} /></div></Card>

    <Dialog isOpen={assignOpen} onClose={() => setAssignOpen(false)} title="Asignar plan" description="Al confirmar, este plan quedará vinculado de forma exclusiva al paciente elegido."><form className="space-y-4" onSubmit={event => { event.preventDefault(); void assign(); }}><select className="form-control" value={patientId} onChange={event => setPatientId(event.target.value)}>{patients.map(person => <option key={person.id} value={person.id}>{person.firstName} {person.lastName}</option>)}</select><div className="flex gap-3"><label className="text-sm"><input type="radio" checked={kind === 'primary'} onChange={() => setKind('primary')} /> Plan principal</label><label className="text-sm"><input type="radio" checked={kind === 'complement'} onChange={() => setKind('complement')} /> Complemento</label></div><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setAssignOpen(false)}>Cancelar</Button><Button type="submit" disabled={!patientId}><Check className="h-4 w-4" />Confirmar</Button></div></form></Dialog>
  </div>;
}

function MealEditor({ recipes, day, meal, index, activity, patientName, updateMeal, updateDay }: { recipes: LibraryContent[]; day: ClinicalMealPlanDay; meal: ClinicalMealPlanMeal; index: number; activity?: RealMealPlanActivity; patientName?: string; updateMeal: (dayId: string, mealId: string, update: (meal: ClinicalMealPlanMeal) => ClinicalMealPlanMeal) => void; updateDay: (dayId: string, update: (day: ClinicalMealPlanDay) => ClinicalMealPlanDay) => void }) {
  return <div className="rounded-xl border border-border-subtle bg-surface-subtle p-3 sm:p-4"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-brand-soft text-xs font-bold text-brand-strong">{index + 1}</span><select className={`${inputClass} min-w-44 flex-1`} aria-label={`Nombre de la comida ${index + 1}`} value={meal.type} onChange={event => updateMeal(day.id, meal.id, current => ({ ...current, type: event.target.value }))}>{mealNames.map(name => <option key={name} value={name}>{name}</option>)}{!mealNames.includes(meal.type as typeof mealNames[number]) && <option value={meal.type}>{meal.type}</option>}</select><Badge variant={statusVariant(activity?.adherenceStatus)}>{statusLabel(activity?.adherenceStatus)}</Badge><Button size="sm" variant="ghost" aria-label={`Quitar ${meal.type}`} onClick={() => updateDay(day.id, current => ({ ...current, meals: current.meals.filter(item => item.id !== meal.id) }))}><Trash2 className="h-4 w-4" /></Button></div>
    <fieldset className="mt-4 space-y-3"><legend className="text-xs font-bold">Elementos de la comida</legend>{meal.items.map((item, itemIndex) => <div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_180px_44px] sm:items-end" key={item.id}><div><label className="mb-1 block text-[11px] text-text-secondary" htmlFor={`item-${item.id}`}>Elemento {itemIndex + 1}</label><input id={`item-${item.id}`} className={inputClass} placeholder="Ej. Yogur natural" value={item.description} onChange={event => updateMeal(day.id, meal.id, current => ({ ...current, items: current.items.map(candidate => candidate.id === item.id ? { ...candidate, description: event.target.value } : candidate) }))} /></div><div><label className="mb-1 block text-[11px] text-text-secondary" htmlFor={`quantity-${item.id}`}>Cantidad opcional</label><input id={`quantity-${item.id}`} className={inputClass} placeholder="Ej. 1 taza" value={item.quantity ?? ''} onChange={event => updateMeal(day.id, meal.id, current => ({ ...current, items: current.items.map(candidate => candidate.id === item.id ? { ...candidate, quantity: event.target.value } : candidate) }))} /></div><Button variant="ghost" aria-label={`Quitar elemento ${itemIndex + 1}`} disabled={meal.items.length <= 1} onClick={() => updateMeal(day.id, meal.id, current => ({ ...current, items: current.items.filter(candidate => candidate.id !== item.id) }))}><Trash2 className="h-4 w-4" /></Button><RealRecipePicker recipes={recipes} value={item.recipeId} onChange={recipeId => updateMeal(day.id, meal.id, current => ({ ...current, items: current.items.map(candidate => candidate.id===item.id ? { ...candidate, recipeId } : candidate) }))} /></div>)}</fieldset>
    <Button className="mt-3" size="sm" variant="secondary" onClick={() => updateMeal(day.id, meal.id, current => ({ ...current, items: [...current.items, { id: crypto.randomUUID(), description: '', quantity: '' }] }))}><Plus className="h-4 w-4" />Agregar elemento</Button><div className="mt-4"><label className="mb-1 block text-xs font-semibold" htmlFor={`alternatives-${meal.id}`}>Alternativas opcionales</label><textarea id={`alternatives-${meal.id}`} className={`${inputClass} min-h-20 resize-y`} placeholder="Opciones de reemplazo para esta comida" value={meal.alternatives ?? ''} onChange={event => updateMeal(day.id, meal.id, current => ({ ...current, alternatives: event.target.value }))} /></div>
    {activity?.patientComment && <div className="mt-4 rounded-xl border border-semantic-warning/40 bg-semantic-warning-bg p-3"><div className="flex items-start gap-2"><MessageSquareText className="mt-0.5 h-4 w-4 shrink-0 text-semantic-warning" /><div><p className="text-[11px] font-bold uppercase tracking-wide text-text-secondary">Comentario de {patientName}</p><p className="mt-1 text-sm">{activity.patientComment}</p></div></div></div>}
  </div>;
}

function TextArea({ label, id, value, onChange }: { label: string; id: string; value: string; onChange: (value: string) => void }) {
  return <div><label className="mb-1 block text-xs font-semibold" htmlFor={`real-plan-${id}`}>{label}</label><textarea id={`real-plan-${id}`} className={`${inputClass} min-h-28 resize-y`} value={value} onChange={event => onChange(event.target.value)} /></div>;
}
import { RealRecipePicker } from '../../../components/domain/RealRecipePicker';
import { loadLibrary, type LibraryContent } from '../../../data/supabase/library.repository';
