import {useCallback,useEffect,useMemo,useState} from 'react';
import {MailPlus,RotateCw,UserPlus,XCircle} from 'lucide-react';
import {RealAnthropometryPatientList} from '../../../components/domain/RealAnthropometryPatientList';
import {useAuth} from '../../../auth/AuthProvider';
import {getSupabaseClient} from '../../../auth/supabase-client';
import {Button} from '../../../components/ui/Button';
import {Card} from '../../../components/ui/Card';
import {Dialog} from '../../../components/ui/Dialog';
import {Badge} from '../../../components/ui/Badge';
import {publicEnvironment} from '../../../config/environment';
import {loadPatientInvitations,revokePatientInvitation,type PatientInvitation} from '../../../data/supabase/patient-profile.repository';

const date=(value:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'medium'}).format(new Date(value));
const invitationLabel={pending:'Pendiente',accepted:'Aceptada',expired:'Vencida',revoked:'Cancelada'} as const;

export function RealPatientsPage(){
 const {accessContext}=useAuth();
 const organizations=useMemo(()=>accessContext?.memberships.filter(m=>m.role==='nutritionist'&&m.membership_status==='active'&&m.organization_status==='active')??[],[accessContext]);
 const [organizationId,setOrganizationId]=useState(organizations[0]?.organization_id??'');
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[sent,setSent]=useState(false),[activationUrl,setActivationUrl]=useState<string|null>(null),[form,setForm]=useState({first_name:'',last_name:'',email:''});
 const [invitations,setInvitations]=useState<PatientInvitation[]>([]),[invitationError,setInvitationError]=useState(''),[refreshKey,setRefreshKey]=useState(0),[activeCount,setActiveCount]=useState(0),[cancelTarget,setCancelTarget]=useState<PatientInvitation|null>(null);
 const organization=organizations.find(item=>item.organization_id===organizationId)??organizations[0]??null;
 useEffect(()=>{if(!organizationId&&organizations[0])setOrganizationId(organizations[0].organization_id);},[organizationId,organizations]);
 const refresh=useCallback(async()=>{try{setInvitationError('');setInvitations(await loadPatientInvitations());}catch(e){setInvitationError((e as Error).message);}},[]);
 useEffect(()=>{void refresh();},[refresh,refreshKey]);
 const send=async(values= form)=>{if(!organization||!publicEnvironment.supabaseUrl)return;setSaving(true);setError(null);setActivationUrl(null);try{const {data:{session}}=await getSupabaseClient().auth.getSession();if(!session)throw new Error('Sesión vencida');const r=await fetch(new URL('/functions/v1/patient-invitations',publicEnvironment.supabaseUrl),{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({organization_id:organization.organization_id,...values})});const p=await r.json() as {message?:string;activation_url?:string};if(!r.ok)throw new Error(p.message);setOpen(false);setForm({first_name:'',last_name:'',email:''});setActivationUrl(p.activation_url??null);setSent(true);setRefreshKey(n=>n+1);}catch(c){setError(c instanceof Error?c.message:'No pudimos enviar la invitación.')}finally{setSaving(false);}};
 const visibleInvitations=invitations.filter(item=>item.organization_id===organization?.organization_id);
 return <main className="mx-auto max-w-4xl space-y-6 p-4 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h1 className="text-2xl font-bold text-text-primary">Pacientes</h1><p className="mt-1 text-sm text-text-secondary">Directorio, invitaciones y acceso a cada ficha clínica.</p></div><Button onClick={()=>setOpen(true)} disabled={!organization}><UserPlus className="h-4 w-4"/>Invitar paciente</Button></div>
 {organizations.length>1&&<label className="form-label max-w-sm">Consultorio<select className="form-control" value={organization?.organization_id??''} onChange={e=>setOrganizationId(e.target.value)}>{organizations.map(item=><option key={item.organization_id} value={item.organization_id}>{item.organization_name}</option>)}</select></label>}
 <RealAnthropometryPatientList organizationId={organization?.organization_id} refreshKey={refreshKey} onCount={setActiveCount}/>
 {activeCount===0&&visibleInvitations.length===0&&<Card highlighted><h2 className="font-bold text-text-primary">Tu primer paciente</h2><p className="mt-2 text-sm text-text-secondary">Invitalo por correo. La ficha quedará vinculada a <b>{organization?.organization_name}</b> y la persona configurará su acceso desde un enlace seguro.</p></Card>}
 <Card className="space-y-4"><div><h2 className="font-bold text-text-primary">Invitaciones</h2><p className="mt-1 text-xs text-text-secondary">Podés reenviar las pendientes o vencidas y cancelar las que ya no correspondan.</p></div>{invitationError?<p role="alert">{invitationError}</p>:visibleInvitations.length?<div className="divide-y divide-border-subtle">{visibleInvitations.map(item=><div key={item.id} className="flex flex-col gap-3 py-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{item.first_name} {item.last_name}</span><Badge variant={item.status==='accepted'?'active':item.status==='pending'?'pending':item.status==='expired'?'medium':'neutral'}>{invitationLabel[item.status]}</Badge></div><p className="truncate text-sm text-text-secondary">{item.email} · enviada {date(item.created_at)}{item.resent_at?` · reenviada ${date(item.resent_at)}`:''}</p></div>{(item.status==='pending'||item.status==='expired')&&<div className="flex gap-2"><Button size="sm" variant="secondary" disabled={saving} onClick={()=>void send({first_name:item.first_name,last_name:item.last_name,email:item.email})}><RotateCw className="h-4 w-4"/>Reenviar</Button><Button size="sm" variant="ghost" disabled={saving} onClick={()=>setCancelTarget(item)}><XCircle className="h-4 w-4"/>Cancelar</Button></div>}</div>)}</div>:<p className="rounded-xl bg-surface-subtle p-4 text-sm text-text-secondary">No hay invitaciones en este consultorio.</p>}{import.meta.env.DEV&&<p className="text-xs text-text-secondary">Los correos locales se consultan en el <a className="font-semibold text-brand-strong underline" href="http://127.0.0.1:54324" target="_blank" rel="noreferrer">Buzón de pruebas</a>.</p>}</Card>
 {sent&&<div role="status" className="rounded-xl border border-success/20 bg-success/10 p-3 text-sm text-success"><MailPlus className="mr-2 inline h-4 w-4"/>Invitación preparada. {activationUrl?<a className="font-semibold underline" href={activationUrl}>Abrir enlace de activación local</a>:'Revisá el correo enviado.'}</div>}{error&&!open&&<p role="alert" className="rounded-xl border border-critical/20 bg-critical/10 p-3 text-sm text-critical">{error}</p>}
 <Dialog isOpen={open} onClose={()=>!saving&&setOpen(false)} title="Invitar paciente" description={`La invitación quedará asociada a ${organization?.organization_name??'este consultorio'}.`}><form onSubmit={e=>{e.preventDefault();void send();}} className="space-y-4">{organizations.length>1&&<label className="form-label">Consultorio<select className="form-control" value={organization?.organization_id??''} onChange={e=>setOrganizationId(e.target.value)}>{organizations.map(item=><option key={item.organization_id} value={item.organization_id}>{item.organization_name}</option>)}</select></label>}<div className="grid gap-3 sm:grid-cols-2"><label className="form-label">Nombre<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})} className="form-control"/></label><label className="form-label">Apellido<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})} className="form-control"/></label></div><label className="form-label">Correo electrónico<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="form-control"/></label>{error&&<p role="alert" className="rounded-xl bg-critical/10 p-3 text-sm text-critical">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?'Enviando…':'Enviar invitación'}</Button></div></form></Dialog>
 {cancelTarget&&<Dialog isOpen onClose={()=>!saving&&setCancelTarget(null)} title="Cancelar invitación" description="El enlace dejará de habilitar el acceso. La operación queda registrada."><div className="space-y-4"><p className="text-sm">Cancelar la invitación de <b>{cancelTarget.first_name} {cancelTarget.last_name}</b>.</p>{error&&<p role="alert" className="rounded-xl bg-critical/10 p-3 text-sm text-critical">{error}</p>}<div className="flex justify-end gap-2"><Button variant="secondary" disabled={saving} onClick={()=>setCancelTarget(null)}>Volver</Button><Button variant="destructive" disabled={saving} onClick={()=>void(async()=>{setSaving(true);setError(null);try{await revokePatientInvitation(cancelTarget.id);setCancelTarget(null);setRefreshKey(n=>n+1);}catch(e){setError((e as Error).message);}finally{setSaving(false);}})()}>{saving?'Cancelando…':'Cancelar invitación'}</Button></div></div></Dialog>}
 </main>;
}
