import { useEffect, useState } from 'react';
import { ChevronRight, CircleDollarSign } from 'lucide-react';
import { getSupabaseClient } from '../../../auth/supabase-client';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Dialog } from '../../../components/ui/Dialog';
import { localDate } from '../../../lib/anthropometry';
import { RealIncomeChart } from '../../../components/domain/RealIncomeChart';
import { civilDate, incomeMetrics, incomeMonths, monthlyIncome } from '../../../lib/realIncome';

type Cita={updated_at:string;id:string;patient_id:string;starts_at:string;time_zone:string;quoted_amount:number;currency:string;payment_status:string;status:string;modality:string};
type Movement={id:string;appointment_id:string;amount:number;currency:string;movement_kind:string;method:string;note:string|null;occurred_at:string;refunded_payment_id:string|null;revision_id?:string;correction_count?:number;original_amount?:number};
type Person={id:string;first_name:string;last_name:string};
const labels:Record<string,string>={paid:'Pagado',partial:'Parcial',pending:'Pendiente',no_charge:'Sin cargo',refunded:'Reembolsado'};
const money=(value:number,currency:string)=>new Intl.NumberFormat('es-AR',{style:'currency',currency}).format(value);
export function RealIncomePage(){
 const [citas,setCitas]=useState<Cita[]>([]);const [movements,setMovements]=useState<Movement[]>([]);const [people,setPeople]=useState<Person[]>([]);
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [currency,setCurrency]=useState('');
 const [patient,setPatient]=useState('');const [payment,setPayment]=useState('');const [modality,setModality]=useState('');
 const [period,setPeriod]=useState('6');const [from,setFrom]=useState(localDate().slice(0,7));const [to,setTo]=useState(localDate().slice(0,7));
 const [active,setActive]=useState('');const [refund,setRefund]=useState('');const [amount,setAmount]=useState('');const [date,setDate]=useState(localDate());const [method,setMethod]=useState('transfer');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [formError,setFormError]=useState('');const [request,setRequest]=useState(()=>crypto.randomUUID());
 const [showPaid,setShowPaid]=useState(true);const [showPending,setShowPending]=useState(true);
 const [correction,setCorrection]=useState('');
 const [priceOpen,setPriceOpen]=useState(false);const [price,setPrice]=useState('');
 async function load(){setLoading(true);try{
  const api=getSupabaseClient().schema('api');const [a,m,p]=await Promise.all([api.from('appointments').select('id,patient_id,starts_at,time_zone,quoted_amount,currency,payment_status,status,modality,updated_at').order('starts_at',{ascending:false}),api.from('income_movements').select('*').order('occurred_at'),api.from('patient_directory').select('id,first_name,last_name')]);
  if(a.error||m.error||p.error)throw new Error('No pudimos cargar Ingresos. Reintentá.');
  setCitas(a.data as Cita[]);setMovements(m.data as Movement[]);setPeople(p.data as Person[]);setError('');
 }catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const currencies=[...new Set(citas.map(a=>a.currency))].sort();const curr=currencies.includes(currency)?currency:currencies[0]||'ARS';
 const name=(id:string)=>{const p=people.find(v=>v.id===id);return p?`${p.first_name} ${p.last_name}`:'Paciente';};
 const net=(id:string)=>movements.filter(m=>m.appointment_id===id).reduce((sum,m)=>sum+(m.movement_kind==='refund'?-m.amount:m.amount),0);
 const scoped=citas.filter(a=>a.currency===curr&&(!patient||a.patient_id===patient)&&(!payment||a.payment_status===payment)&&(!modality||a.modality===modality));
 const scopedMovements=movements.filter(m=>scoped.some(a=>a.id===m.appointment_id));
 const today=new Date();const start=new Date(today.getFullYear(),today.getMonth()-(Number(period)||1)+1,1);
 const civil=civilDate;
 const monthOf=(m:Movement)=>civil(m.occurred_at,citas.find(a=>a.id===m.appointment_id)?.time_zone||'UTC').slice(0,7);
 const dataMonths=[...scoped.map(a=>civil(a.starts_at,a.time_zone).slice(0,7)),...scopedMovements.map(monthOf)].sort();
 const first=period==='custom'?from:period==='all'?dataMonths[0]||localDate().slice(0,7):localDate(start).slice(0,7);
 const last=period==='custom'?to:period==='all'?dataMonths.at(-1)||localDate().slice(0,7):localDate().slice(0,7);
 const keys=incomeMonths(first,last);
 const chart=monthlyIncome(keys||[],scoped,scopedMovements);
 const metrics=incomeMetrics(scoped,scopedMovements);
 const selected=citas.find(a=>a.id===active);const history=movements.filter(m=>m.appointment_id===active);
 const refundable=history.filter(m=>m.movement_kind==='payment').map(m=>({...m,balance:m.amount-history.filter(r=>r.refunded_payment_id===m.id).reduce((sum,r)=>sum+r.amount,0)})).filter(m=>m.balance>0);
 const editing=history.find(m=>m.id===correction&&m.movement_kind==='payment');
 const limit=editing?Math.max(editing.amount,selected?selected.quoted_amount-net(selected.id)+editing.amount:0):refund?refundable.find(m=>m.id===refund)?.balance??0:selected?Math.max(0,selected.quoted_amount-net(selected.id)):0;
 function open(a:Cita){setPriceOpen(false);setPrice(String(a.quoted_amount));setActive(a.id);setCorrection('');setMethod('transfer');setRefund('');setAmount(String(Math.max(0,a.quoted_amount-net(a.id))));setDate(civil(new Date().toISOString(),a.time_zone));setNote('');setFormError('');setRequest(crypto.randomUUID());}
 async function savePrice(e:React.FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);setFormError('');try{
 const {error}=await getSupabaseClient().schema('api').rpc('update_income_appointment_price',{p_appointment:selected.id,p_expected:selected.updated_at,p_amount:Number(price)});
 if(error)throw new Error(error.message);
 await load();setPriceOpen(false);if(!refund&&!correction)setAmount(String(Math.max(0,Number(price)-net(selected.id))));
 }catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);setFormError('');try{
  const api=getSupabaseClient().schema('api');
  const {error}=editing?await api.rpc('correct_income_payment',{p_payment:editing.id,p_expected:editing.revision_id||editing.id,p_request:request,p_amount:Number(amount),p_date:date,p_method:method,p_note:note}):await api.rpc('record_income_movement',{p_appointment:selected.id,p_request:request,p_amount:Number(amount),p_date:date,p_method:method,p_note:note,...(refund?{p_refund:refund}:{})});
  if(error)throw new Error(error.message);setActive('');await load();
 }catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 return <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6"><div className="flex gap-2 items-center"><CircleDollarSign className="text-brand-strong"/><h1 className="text-2xl font-bold">Ingresos</h1></div><p className="text-sm text-text-secondary">Cobros manuales de tus citas. NutriSoft no procesa pagos ni emite comprobantes.</p>
 {error&&<Card><p role="alert">{error}</p><Button onClick={()=>void load()}>Reintentar</Button></Card>}{loading?<p role="status">Cargando ingresos…</p>:!error&&<>
 <Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="form-label">Moneda<select className="form-control" value={curr} onChange={e=>setCurrency(e.target.value)}>{(currencies.length?currencies:['ARS']).map(c=><option key={c}>{c}</option>)}</select></label><label className="form-label">Paciente<select className="form-control" value={patient} onChange={e=>setPatient(e.target.value)}><option value="">Todos</option>{people.map(p=><option key={p.id} value={p.id}>{name(p.id)}</option>)}</select></label><label className="form-label">Pago<select className="form-control" value={payment} onChange={e=>setPayment(e.target.value)}><option value="">Todos</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="form-label">Modalidad<select className="form-control" value={modality} onChange={e=>setModality(e.target.value)}><option value="">Todas</option><option value="virtual">Virtual</option><option value="in_person">Presencial</option></select></label></div></Card>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Cobrado neto',metrics.paid,'Cobros menos devoluciones, con correcciones aplicadas.'],['Pendiente',metrics.pending,'Saldo por cobrar de citas pendientes o parciales.'],['Proyectado',metrics.projected,'Importe total de próximas citas solicitadas o confirmadas; puede incluir anticipos ya cobrados.'],['No cobrado por cancelación',metrics.lost,'Importe de citas canceladas o ausentes resueltas sin cargo.'],['Parciales por completar',metrics.partial,'Parte del saldo pendiente de citas con pago parcial; no se suma nuevamente.']].map(([label,value,hint])=><Card key={label}><p className="text-sm text-text-secondary">{label}</p><p className="text-xl font-bold break-words">{money(Number(value),curr)}</p><p className="mt-2 text-xs text-text-secondary">{hint}</p></Card>)}</div><p className="text-xs text-text-secondary">Resumen de todo el historial con los filtros superiores. El período siguiente afecta sólo al gráfico. Estos indicadores no se suman entre sí.</p>
 <Card className="space-y-4"><h2 className="font-bold">Cobros y pendientes · {curr}</h2><p className="text-xs text-text-secondary">Neto por fecha de movimiento; pendiente por fecha de cita. Las devoluciones pueden generar un neto mensual negativo.</p><div className="flex flex-wrap gap-1">{[['1','Mes actual'],['3','3 meses'],['6','6 meses'],['12','12 meses'],['all','Todo'],['custom','Personalizado']].map(([k,l])=><Button key={k} variant={period===k?'primary':'ghost'} aria-pressed={period===k} onClick={()=>setPeriod(k!)}>{l}</Button>)}</div>
 {period==='custom'&&<div className="grid gap-3 sm:grid-cols-2"><label className="form-label">Desde<input className="form-control" type="month" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label className="form-label">Hasta<input className="form-control" type="month" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></div>}
 {!keys?<p role="alert">Elegí un rango válido de hasta 20 años.</p>:<RealIncomeChart rows={chart} currency={curr} showPaid={showPaid} showPending={showPending}/>}
 <div className="flex gap-4 text-sm"><label><input type="checkbox" checked={showPaid} disabled={showPaid&&!showPending} onChange={e=>setShowPaid(e.target.checked)}/> Cobrado neto</label><label><input type="checkbox" checked={showPending} disabled={showPending&&!showPaid} onChange={e=>setShowPending(e.target.checked)}/> Pendiente</label></div></Card>
 <Card><h2 className="font-bold mb-3">Citas y cobros</h2><p className="text-xs text-text-secondary mb-3">Abrí una fila para registrar, corregir cobros o anotar reembolsos.</p>{!scoped.length?<p>No hay citas para estos filtros.</p>:scoped.map(a=><button key={a.id} className="flex w-full flex-wrap items-center gap-3 border-t border-border-subtle py-4 text-left hover:bg-surface-subtle" onClick={()=>open(a)}><span className="min-w-0 flex-1"><strong className="block">{name(a.patient_id)}</strong><span className="text-xs">{new Date(a.starts_at).toLocaleDateString('es-AR',{timeZone:a.time_zone})} · {a.modality==='virtual'?'Virtual':'Presencial'}</span></span><span className="text-sm">{money(net(a.id),a.currency)} / {money(a.quoted_amount,a.currency)}<span className="block text-xs text-text-secondary">{labels[a.payment_status]}</span></span><ChevronRight className="h-4 w-4"/></button>)}</Card>
 </>}
 <Dialog isOpen={!!selected} onClose={()=>{if(!busy)setActive('');}} title="Cobros de la cita" description="Registro interno; no mueve dinero ni cambia el estado de la cita.">{selected&&<div className="space-y-4"><p className="font-bold">{name(selected.patient_id)} · {money(selected.quoted_amount,selected.currency)}</p><p>Neto registrado: {money(net(selected.id),selected.currency)}</p>
 {net(selected.id)>selected.quoted_amount&&<p className="rounded-xl bg-surface-subtle p-3 text-sm">El neto cobrado supera el precio en {money(net(selected.id)-selected.quoted_amount,selected.currency)}. No se devolvió dinero automáticamente; podés registrar un reembolso si corresponde.</p>}
 {!priceOpen?<Button variant="secondary" disabled={busy} onClick={()=>{setPrice(String(selected.quoted_amount));setPriceOpen(true);setFormError('');}}>Editar precio de la cita</Button>:<form onSubmit={e=>void savePrice(e)} className="space-y-3 rounded-xl border border-border-subtle p-3"><p className="text-sm">Cambia sólo el precio acordado. Conserva cobros, moneda, fecha y estado de la cita.</p><label className="form-label">Precio de la cita ({selected.currency})<input className="form-control" type="number" min="0" max="9999999999.99" step="0.01" required value={price} disabled={busy} onChange={e=>setPrice(e.target.value)}/></label>{Number(price)<net(selected.id)&&<p className="text-sm">El nuevo precio es menor que lo cobrado. Guardarlo no genera un reembolso.</p>}{selected.payment_status==='no_charge'&&<p className="text-sm">La cita seguirá sin cargo; editar el precio no cambia esa decisión.</p>}<div className="flex flex-wrap gap-2"><Button type="button" variant="ghost" disabled={busy} onClick={()=>{setPriceOpen(false);setFormError('');}}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Guardando…':'Guardar precio'}</Button></div>{formError&&<p role="alert">{formError}</p>}</form>}
<div className="space-y-2">{history.map(m=><div key={m.id} className="border-b border-border-subtle py-2 text-sm"><p>{m.movement_kind==='refund'?'Reembolso':'Cobro'} · {money(m.amount,m.currency)} · {new Date(m.occurred_at).toLocaleDateString('es-AR',{timeZone:selected.time_zone})}</p>{m.correction_count?<p className="text-xs text-text-secondary">Corregido · Original: {money(m.original_amount??m.amount,m.currency)}</p>:null}{m.note&&<p className="break-words text-xs text-text-secondary">{m.note}</p>}</div>)}</div>
 {!priceOpen&&<form onSubmit={e=>void submit(e)} className="space-y-3"><fieldset disabled={busy} className="space-y-3"><label className="form-label">Operación<select className="form-control" value={correction?'correct:'+correction:refund} onChange={e=>{
 const value=e.target.value;const corrected=value.startsWith('correct:')?history.find(m=>m.id===value.slice(8)):undefined;
 setCorrection(corrected?.id||'');setRefund(corrected?'':value);
 setAmount(String(corrected?.amount??(value?refundable.find(m=>m.id===value)?.balance??0:Math.max(0,selected.quoted_amount-net(selected.id)))));
 setDate(corrected?civil(corrected.occurred_at,selected.time_zone):civil(new Date().toISOString(),selected.time_zone));
 setMethod(corrected?.method||'transfer');setNote(corrected?.note||'');setRequest(crypto.randomUUID());setFormError('');
}}><option value="">Registrar cobro</option>{history.filter(m=>m.movement_kind==='payment').map(m=><option key={'correct:'+m.id} value={'correct:'+m.id}>Corregir cobro del {new Date(m.occurred_at).toLocaleDateString('es-AR',{timeZone:selected.time_zone})} · {money(m.amount,m.currency)}</option>)}{refundable.map(m=><option key={m.id} value={m.id}>Reembolso del {new Date(m.occurred_at).toLocaleDateString('es-AR',{timeZone:selected.time_zone})} · hasta {money(m.balance,m.currency)}</option>)}</select></label>{editing&&<p className="rounded-xl bg-surface-subtle p-3 text-sm">Corrige un error de carga: no registra una devolución. El original se conserva y los totales se recalculan con estos datos. No hace falta indicar motivo.</p>}<label className="form-label">Monto ({selected.currency})<input className="form-control" required type="number" step="0.01" min="0.01" max={limit} value={amount} onChange={e=>{setAmount(e.target.value);setRequest(crypto.randomUUID());}}/></label><label className="form-label">Fecha<input className="form-control" required type="date" max={civil(new Date().toISOString(),selected.time_zone)} value={date} onChange={e=>{setDate(e.target.value);setRequest(crypto.randomUUID());}}/></label><label className="form-label">Medio<select className="form-control" value={method} onChange={e=>{setMethod(e.target.value);setRequest(crypto.randomUUID());}}><option value="transfer">Transferencia</option><option value="cash">Efectivo</option><option value="other">Otro</option></select></label><label className="form-label">Nota opcional<textarea className="form-control" maxLength={500} value={note} onChange={e=>{setNote(e.target.value);setRequest(crypto.randomUUID());}}/></label><Button type="submit" disabled={busy||limit<=0||(!refund&&!editing&&selected.payment_status==='no_charge')}>{busy?'Guardando…':editing?'Guardar corrección':refund?'Registrar reembolso':'Registrar cobro'}</Button></fieldset>{formError&&<p role="alert">{formError}</p>}</form>}</div>}</Dialog>
 </div>;
}
