import {useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Inbox,CheckCircle2,BellRing} from 'lucide-react';
import {getSupabaseClient} from '../../../auth/supabase-client';
import {questionSchema} from '../../../lib/checkinQuestions';
import type {Database} from '../../../types/database.types';
import {Card} from '../../../components/ui/Card';
import {Button} from '../../../components/ui/Button';
import {Dialog} from '../../../components/ui/Dialog';

type Alert=Database['api']['Views']['attention_inbox']['Row'];
const states:Record<string,string>={unresolved:'Sin revisar',acknowledged:'En revisión',resolved:'Resuelta'};
const reasons:Record<string,string>={CUSTOM_CHECKIN:'Respuesta señalada por tus reglas',LOW_ENERGY:'Energía baja registrada',LOW_ADHERENCE:'Dificultad para seguir el plan',HELP_REQUESTED:'Pedido de ayuda',DELAYED_CHECKIN:'Check-in pendiente'};
const date=(value:string|null)=>value?new Date(value).toLocaleString('es-AR',{dateStyle:'medium',timeStyle:'short'}):'—';
export function RealInboxPage(){
 const [rows,setRows]=useState<Alert[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [filter,setFilter]=useState('pending'),[search,setSearch]=useState(''),[high,setHigh]=useState(false),[selected,setSelected]=useState<Alert|null>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const {data,error:e}=await getSupabaseClient().schema('api').from('attention_inbox').select('*').order('created_at',{ascending:false});if(e)throw e;setRows(data??[]);}catch{setRows([]);setError('No pudimos actualizar la bandeja. Reintentá antes de gestionar un aviso.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 async function act(resolve:boolean){if(!selected?.id)return;setBusy(true);setError('');try{const api=getSupabaseClient().schema('api');const result=resolve?await api.rpc('resolve_alert',{p_alert_id:selected.id,p_notes:note}):await api.rpc('acknowledge_alert',{p_alert_id:selected.id});if(result.error||!result.data)throw new Error(result.error?.message??'No se confirmó el cambio.');setSelected(null);setNotice(resolve?'Aviso resuelto. Queda disponible en el historial.':'Aviso en revisión. Sigue entre los pendientes.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const pending=rows.filter(a=>a.status!=='resolved');
 const shown=rows.filter(a=>(filter==='all'||(filter==='pending'?a.status!=='resolved':a.status===filter))&&(!high||a.priority==='high')&&`${a.patient_first_name} ${a.patient_last_name}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>Number(b.priority==='high')-Number(a.priority==='high'));
 const questions=questionSchema.array().safeParse(selected?.questions);
 const matches=Array.isArray(selected?.alert_matches)?selected.alert_matches:[];
 const answers=selected?.question_answers as Record<string,string>|null;
 return <div className="max-w-6xl mx-auto p-4 sm:p-6 space-y-5">
 <header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Inbox className="text-brand-strong"/>Bandeja de atención</h1><p className="text-sm text-text-secondary mt-1">Revisá las señales de tus pacientes y decidí el próximo paso.</p></div><Button variant="secondary" disabled={loading||busy} onClick={()=>void refresh()}>Actualizar</Button></header>
 <div className="grid grid-cols-3 gap-2">{[['Pendientes',pending.length],['Prioridad alta',pending.filter(a=>a.priority==='high').length],['En revisión',pending.filter(a=>a.status==='acknowledged').length]].map(([label,n])=><Card key={label} className="!p-3"><p className="text-xs text-text-secondary">{label}</p><strong className="text-2xl">{loading||error?'—':n}</strong></Card>)}</div>
 <Card className="space-y-3"><div className="flex flex-wrap gap-1" aria-label="Estado de los avisos">{[['pending','Pendientes'],['acknowledged','En revisión'],['resolved','Resueltos'],['all','Todos']].map(([v,label])=><Button key={v} variant={filter===v?'secondary':'ghost'} aria-pressed={filter===v} onClick={()=>setFilter(v!)}>{label}</Button>)}</div><div className="flex flex-wrap items-center gap-3"><label className="form-label flex-1 min-w-0">Buscar paciente<input className="form-control" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre o apellido"/></label><label className="flex items-center gap-2 min-h-11 text-sm"><input type="checkbox" checked={high} onChange={e=>setHigh(e.target.checked)}/>Sólo prioridad alta</label></div></Card>
 {notice&&<p role="status" className="text-sm text-brand-strong">{notice}</p>}{error&&!selected&&<p role="alert">{error}</p>}
 {loading?<p role="status">Cargando avisos…</p>:!error&&shown.length===0?<Card className="py-8 text-center space-y-2"><CheckCircle2 className="mx-auto text-brand-strong"/><h2 className="font-semibold">{rows.length?'Sin avisos para estos filtros':'No hay avisos registrados'}</h2><p className="text-sm text-text-secondary">La ausencia de avisos no significa ausencia de dificultades. Podés consultar el seguimiento de tus pacientes.</p><Button asChild variant="ghost"><Link to="/professional/checkins">Ver check-ins</Link></Button></Card>:shown.map(a=><button key={a.id} type="button" className="w-full text-left rounded-2xl border border-border-subtle bg-surface p-4 hover:bg-surface-subtle focus-visible:ring-2 focus-visible:ring-brand-strong" onClick={()=>{setSelected(a);setNote('');setError('');}}><div className="flex flex-wrap justify-between gap-2"><strong>{a.patient_first_name} {a.patient_last_name}</strong><span className="text-xs rounded-full bg-surface-subtle px-2 py-1">{states[a.status??'']??a.status} · {a.priority==='high'?'Prioridad alta':'Prioridad media'}</span></div><p className="text-sm mt-2 flex gap-2"><BellRing className="h-4 w-4 shrink-0 text-brand-strong"/>{reasons[a.rule_code??'']??'Respuesta para revisar'}</p><div className="flex flex-wrap justify-between gap-2 mt-2 text-xs text-text-secondary"><span>{date(a.created_at)}</span><span className="text-brand-strong">Revisar aviso →</span></div></button>)}
 <p className="text-xs text-text-secondary">Reconocer un aviso lo deja en revisión; resolverlo conserva su historial. Estas señales no son diagnósticos ni avisos de emergencia.</p>
 {selected&&<Dialog isOpen onClose={()=>{if(!busy)setSelected(null);}} title={`${selected.patient_first_name} ${selected.patient_last_name}`} description={`${states[selected.status??'']} · ${date(selected.created_at)}`}><div className="space-y-4"><h3 className="font-semibold">{reasons[selected.rule_code??'']??'Respuesta para revisar'}</h3>
 {questions.success?questions.data.filter(q=>matches.includes(q.id)).map(q=><div key={q.id} className="rounded-xl bg-surface-subtle p-3"><p className="text-sm">{q.text}</p><strong className="block mt-1">{answers?.[q.id]??'Sin respuesta'}</strong></div>):<div className="text-sm space-y-1">{selected.energy!=null&&<p>Energía: {selected.energy}/5</p>}{selected.adherence!=null&&<p>Seguimiento del plan: {selected.adherence}/5</p>}{selected.help_requested&&<p>El paciente solicitó ayuda.</p>}{selected.notes&&<p className="whitespace-pre-wrap">{selected.notes}</p>}</div>}
 <p className="text-sm text-text-secondary">{selected.recommended_action}</p><Button asChild variant="secondary"><Link to={`/professional/patients/${selected.patient_id}?tab=checkins`}>Abrir ficha y check-ins</Link></Button>
 {selected.acknowledged_at&&<p className="text-xs">En revisión desde {date(selected.acknowledged_at)}</p>}
 {selected.status==='resolved'?<div className="text-sm"><p>Resuelta el {date(selected.resolved_at)}</p>{selected.resolution_notes&&<p className="whitespace-pre-wrap mt-2">{selected.resolution_notes}</p>}</div>:<><label className="form-label">Nota de resolución (opcional)<textarea className="form-control" maxLength={500} disabled={busy} value={note} onChange={e=>setNote(e.target.value)} placeholder="Qué acción realizaste"/></label><p className="text-xs text-text-secondary">Al resolver confirmás que revisaste el aviso. No se envía un mensaje al paciente.</p><div className="flex flex-wrap gap-2">{selected.status==='unresolved'&&<Button variant="secondary" disabled={busy} onClick={()=>void act(false)}>Marcar en revisión</Button>}<Button disabled={busy} onClick={()=>void act(true)}>{busy?'Guardando…':'Resolver aviso'}</Button></div></>}{error&&<p role="alert">{error}</p>}</div></Dialog>}
 </div>;
}
